# Copyright (c) 2017-2020 VMware, Inc. or its affiliates
# SPDX-License-Identifier: Apache-2.0

PLATFORM: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1.14'

inputs:
- name: gpupgrade_src
- name: bats

run:
  path: bash
  args:
  - -c
  - |
    set -ex

    apt update
    apt install -y rsync

    export TERM=linux
    ./bats/install.sh /usr/local

    export GOFLAGS="-mod=readonly" # do not update dependencies during build
    cd gpupgrade_src
    make
    make check --keep-going
