---
- hosts: all
  gather_facts: False
  tasks:

- name: jumpbox configuration
  gather_facts: False
  hosts: jumpbox
  become: yes
  become_method: sudo
  roles:
    - jumpbox

- name: data warehouse controller configuration
  gather_facts: False
  hosts: dwcontroller
  become: yes
  become_method: sudo
  roles:
    - dwcontroller

- name: data warehouse data node configuration
  gather_facts: False
  hosts: dwdatanodes
  become: yes
  become_method: sudo
  roles:
    - dwdatanode
