// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cli_to_hub.proto

package idl

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpgradeSteps int32

const (
	UpgradeSteps_UNKNOWN_STEP            UpgradeSteps = 0
	UpgradeSteps_CONFIG                  UpgradeSteps = 1
	UpgradeSteps_START_AGENTS            UpgradeSteps = 2
	UpgradeSteps_INIT_TARGET_CLUSTER     UpgradeSteps = 3
	UpgradeSteps_SHUTDOWN_TARGET_CLUSTER UpgradeSteps = 4
	UpgradeSteps_CHECK_MASTER            UpgradeSteps = 5
	UpgradeSteps_CHECK_PRIMARIES         UpgradeSteps = 6
	UpgradeSteps_RESTART_TARGET_CLUSTER  UpgradeSteps = 7
	UpgradeSteps_SHUTDOWN_CLUSTERS       UpgradeSteps = 8
	UpgradeSteps_UPGRADE_MASTER          UpgradeSteps = 9
	UpgradeSteps_COPY_MASTER             UpgradeSteps = 10
	UpgradeSteps_UPGRADE_PRIMARIES       UpgradeSteps = 11
	UpgradeSteps_START_TARGET_CLUSTER    UpgradeSteps = 12
	UpgradeSteps_RECONFIGURE_PORTS       UpgradeSteps = 13
)

var UpgradeSteps_name = map[int32]string{
	0:  "UNKNOWN_STEP",
	1:  "CONFIG",
	2:  "START_AGENTS",
	3:  "INIT_TARGET_CLUSTER",
	4:  "SHUTDOWN_TARGET_CLUSTER",
	5:  "CHECK_MASTER",
	6:  "CHECK_PRIMARIES",
	7:  "RESTART_TARGET_CLUSTER",
	8:  "SHUTDOWN_CLUSTERS",
	9:  "UPGRADE_MASTER",
	10: "COPY_MASTER",
	11: "UPGRADE_PRIMARIES",
	12: "START_TARGET_CLUSTER",
	13: "RECONFIGURE_PORTS",
}

var UpgradeSteps_value = map[string]int32{
	"UNKNOWN_STEP":            0,
	"CONFIG":                  1,
	"START_AGENTS":            2,
	"INIT_TARGET_CLUSTER":     3,
	"SHUTDOWN_TARGET_CLUSTER": 4,
	"CHECK_MASTER":            5,
	"CHECK_PRIMARIES":         6,
	"RESTART_TARGET_CLUSTER":  7,
	"SHUTDOWN_CLUSTERS":       8,
	"UPGRADE_MASTER":          9,
	"COPY_MASTER":             10,
	"UPGRADE_PRIMARIES":       11,
	"START_TARGET_CLUSTER":    12,
	"RECONFIGURE_PORTS":       13,
}

func (x UpgradeSteps) String() string {
	return proto.EnumName(UpgradeSteps_name, int32(x))
}

func (UpgradeSteps) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{0}
}

type StepStatus int32

const (
	StepStatus_UNKNOWN_STATUS StepStatus = 0
	StepStatus_PENDING        StepStatus = 1
	StepStatus_RUNNING        StepStatus = 2
	StepStatus_COMPLETE       StepStatus = 3
	StepStatus_FAILED         StepStatus = 4
)

var StepStatus_name = map[int32]string{
	0: "UNKNOWN_STATUS",
	1: "PENDING",
	2: "RUNNING",
	3: "COMPLETE",
	4: "FAILED",
}

var StepStatus_value = map[string]int32{
	"UNKNOWN_STATUS": 0,
	"PENDING":        1,
	"RUNNING":        2,
	"COMPLETE":       3,
	"FAILED":         4,
}

func (x StepStatus) String() string {
	return proto.EnumName(StepStatus_name, int32(x))
}

func (StepStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{1}
}

type Chunk_Type int32

const (
	Chunk_UNKNOWN Chunk_Type = 0
	Chunk_STDOUT  Chunk_Type = 1
	Chunk_STDERR  Chunk_Type = 2
)

var Chunk_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "STDOUT",
	2: "STDERR",
}

var Chunk_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"STDOUT":  1,
	"STDERR":  2,
}

func (x Chunk_Type) String() string {
	return proto.EnumName(Chunk_Type_name, int32(x))
}

func (Chunk_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{18, 0}
}

type InitializeRequest struct {
	OldBinDir            string   `protobuf:"bytes,1,opt,name=oldBinDir,proto3" json:"oldBinDir,omitempty"`
	NewBinDir            string   `protobuf:"bytes,2,opt,name=newBinDir,proto3" json:"newBinDir,omitempty"`
	OldPort              int32    `protobuf:"varint,3,opt,name=oldPort,proto3" json:"oldPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeRequest) Reset()         { *m = InitializeRequest{} }
func (m *InitializeRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeRequest) ProtoMessage()    {}
func (*InitializeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{0}
}

func (m *InitializeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeRequest.Unmarshal(m, b)
}
func (m *InitializeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeRequest.Marshal(b, m, deterministic)
}
func (m *InitializeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeRequest.Merge(m, src)
}
func (m *InitializeRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeRequest.Size(m)
}
func (m *InitializeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeRequest proto.InternalMessageInfo

func (m *InitializeRequest) GetOldBinDir() string {
	if m != nil {
		return m.OldBinDir
	}
	return ""
}

func (m *InitializeRequest) GetNewBinDir() string {
	if m != nil {
		return m.NewBinDir
	}
	return ""
}

func (m *InitializeRequest) GetOldPort() int32 {
	if m != nil {
		return m.OldPort
	}
	return 0
}

type InitializeCreateClusterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitializeCreateClusterRequest) Reset()         { *m = InitializeCreateClusterRequest{} }
func (m *InitializeCreateClusterRequest) String() string { return proto.CompactTextString(m) }
func (*InitializeCreateClusterRequest) ProtoMessage()    {}
func (*InitializeCreateClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{1}
}

func (m *InitializeCreateClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitializeCreateClusterRequest.Unmarshal(m, b)
}
func (m *InitializeCreateClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitializeCreateClusterRequest.Marshal(b, m, deterministic)
}
func (m *InitializeCreateClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitializeCreateClusterRequest.Merge(m, src)
}
func (m *InitializeCreateClusterRequest) XXX_Size() int {
	return xxx_messageInfo_InitializeCreateClusterRequest.Size(m)
}
func (m *InitializeCreateClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_InitializeCreateClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_InitializeCreateClusterRequest proto.InternalMessageInfo

type ExecuteRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExecuteRequest) Reset()         { *m = ExecuteRequest{} }
func (m *ExecuteRequest) String() string { return proto.CompactTextString(m) }
func (*ExecuteRequest) ProtoMessage()    {}
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{2}
}

func (m *ExecuteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExecuteRequest.Unmarshal(m, b)
}
func (m *ExecuteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExecuteRequest.Marshal(b, m, deterministic)
}
func (m *ExecuteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExecuteRequest.Merge(m, src)
}
func (m *ExecuteRequest) XXX_Size() int {
	return xxx_messageInfo_ExecuteRequest.Size(m)
}
func (m *ExecuteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExecuteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExecuteRequest proto.InternalMessageInfo

type FinalizeRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FinalizeRequest) Reset()         { *m = FinalizeRequest{} }
func (m *FinalizeRequest) String() string { return proto.CompactTextString(m) }
func (*FinalizeRequest) ProtoMessage()    {}
func (*FinalizeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{3}
}

func (m *FinalizeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FinalizeRequest.Unmarshal(m, b)
}
func (m *FinalizeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FinalizeRequest.Marshal(b, m, deterministic)
}
func (m *FinalizeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FinalizeRequest.Merge(m, src)
}
func (m *FinalizeRequest) XXX_Size() int {
	return xxx_messageInfo_FinalizeRequest.Size(m)
}
func (m *FinalizeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FinalizeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FinalizeRequest proto.InternalMessageInfo

type RestartAgentsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartAgentsRequest) Reset()         { *m = RestartAgentsRequest{} }
func (m *RestartAgentsRequest) String() string { return proto.CompactTextString(m) }
func (*RestartAgentsRequest) ProtoMessage()    {}
func (*RestartAgentsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{4}
}

func (m *RestartAgentsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartAgentsRequest.Unmarshal(m, b)
}
func (m *RestartAgentsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartAgentsRequest.Marshal(b, m, deterministic)
}
func (m *RestartAgentsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartAgentsRequest.Merge(m, src)
}
func (m *RestartAgentsRequest) XXX_Size() int {
	return xxx_messageInfo_RestartAgentsRequest.Size(m)
}
func (m *RestartAgentsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartAgentsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestartAgentsRequest proto.InternalMessageInfo

type RestartAgentsReply struct {
	AgentHosts           []string `protobuf:"bytes,1,rep,name=agentHosts,proto3" json:"agentHosts,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestartAgentsReply) Reset()         { *m = RestartAgentsReply{} }
func (m *RestartAgentsReply) String() string { return proto.CompactTextString(m) }
func (*RestartAgentsReply) ProtoMessage()    {}
func (*RestartAgentsReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{5}
}

func (m *RestartAgentsReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestartAgentsReply.Unmarshal(m, b)
}
func (m *RestartAgentsReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestartAgentsReply.Marshal(b, m, deterministic)
}
func (m *RestartAgentsReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestartAgentsReply.Merge(m, src)
}
func (m *RestartAgentsReply) XXX_Size() int {
	return xxx_messageInfo_RestartAgentsReply.Size(m)
}
func (m *RestartAgentsReply) XXX_DiscardUnknown() {
	xxx_messageInfo_RestartAgentsReply.DiscardUnknown(m)
}

var xxx_messageInfo_RestartAgentsReply proto.InternalMessageInfo

func (m *RestartAgentsReply) GetAgentHosts() []string {
	if m != nil {
		return m.AgentHosts
	}
	return nil
}

type StopServicesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServicesRequest) Reset()         { *m = StopServicesRequest{} }
func (m *StopServicesRequest) String() string { return proto.CompactTextString(m) }
func (*StopServicesRequest) ProtoMessage()    {}
func (*StopServicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{6}
}

func (m *StopServicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServicesRequest.Unmarshal(m, b)
}
func (m *StopServicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServicesRequest.Marshal(b, m, deterministic)
}
func (m *StopServicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServicesRequest.Merge(m, src)
}
func (m *StopServicesRequest) XXX_Size() int {
	return xxx_messageInfo_StopServicesRequest.Size(m)
}
func (m *StopServicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopServicesRequest proto.InternalMessageInfo

type StopServicesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopServicesReply) Reset()         { *m = StopServicesReply{} }
func (m *StopServicesReply) String() string { return proto.CompactTextString(m) }
func (*StopServicesReply) ProtoMessage()    {}
func (*StopServicesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{7}
}

func (m *StopServicesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopServicesReply.Unmarshal(m, b)
}
func (m *StopServicesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopServicesReply.Marshal(b, m, deterministic)
}
func (m *StopServicesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopServicesReply.Merge(m, src)
}
func (m *StopServicesReply) XXX_Size() int {
	return xxx_messageInfo_StopServicesReply.Size(m)
}
func (m *StopServicesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopServicesReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopServicesReply proto.InternalMessageInfo

type UpgradeStepStatus struct {
	Step                 UpgradeSteps `protobuf:"varint,1,opt,name=step,proto3,enum=idl.UpgradeSteps" json:"step,omitempty"`
	Status               StepStatus   `protobuf:"varint,2,opt,name=status,proto3,enum=idl.StepStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *UpgradeStepStatus) Reset()         { *m = UpgradeStepStatus{} }
func (m *UpgradeStepStatus) String() string { return proto.CompactTextString(m) }
func (*UpgradeStepStatus) ProtoMessage()    {}
func (*UpgradeStepStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{8}
}

func (m *UpgradeStepStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeStepStatus.Unmarshal(m, b)
}
func (m *UpgradeStepStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeStepStatus.Marshal(b, m, deterministic)
}
func (m *UpgradeStepStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeStepStatus.Merge(m, src)
}
func (m *UpgradeStepStatus) XXX_Size() int {
	return xxx_messageInfo_UpgradeStepStatus.Size(m)
}
func (m *UpgradeStepStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeStepStatus.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeStepStatus proto.InternalMessageInfo

func (m *UpgradeStepStatus) GetStep() UpgradeSteps {
	if m != nil {
		return m.Step
	}
	return UpgradeSteps_UNKNOWN_STEP
}

func (m *UpgradeStepStatus) GetStatus() StepStatus {
	if m != nil {
		return m.Status
	}
	return StepStatus_UNKNOWN_STATUS
}

type CountPerDb struct {
	DbName               string   `protobuf:"bytes,1,opt,name=DbName,proto3" json:"DbName,omitempty"`
	AoCount              int32    `protobuf:"varint,2,opt,name=AoCount,proto3" json:"AoCount,omitempty"`
	HeapCount            int32    `protobuf:"varint,3,opt,name=HeapCount,proto3" json:"HeapCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CountPerDb) Reset()         { *m = CountPerDb{} }
func (m *CountPerDb) String() string { return proto.CompactTextString(m) }
func (*CountPerDb) ProtoMessage()    {}
func (*CountPerDb) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{9}
}

func (m *CountPerDb) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CountPerDb.Unmarshal(m, b)
}
func (m *CountPerDb) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CountPerDb.Marshal(b, m, deterministic)
}
func (m *CountPerDb) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CountPerDb.Merge(m, src)
}
func (m *CountPerDb) XXX_Size() int {
	return xxx_messageInfo_CountPerDb.Size(m)
}
func (m *CountPerDb) XXX_DiscardUnknown() {
	xxx_messageInfo_CountPerDb.DiscardUnknown(m)
}

var xxx_messageInfo_CountPerDb proto.InternalMessageInfo

func (m *CountPerDb) GetDbName() string {
	if m != nil {
		return m.DbName
	}
	return ""
}

func (m *CountPerDb) GetAoCount() int32 {
	if m != nil {
		return m.AoCount
	}
	return 0
}

func (m *CountPerDb) GetHeapCount() int32 {
	if m != nil {
		return m.HeapCount
	}
	return 0
}

type CheckObjectCountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckObjectCountRequest) Reset()         { *m = CheckObjectCountRequest{} }
func (m *CheckObjectCountRequest) String() string { return proto.CompactTextString(m) }
func (*CheckObjectCountRequest) ProtoMessage()    {}
func (*CheckObjectCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{10}
}

func (m *CheckObjectCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckObjectCountRequest.Unmarshal(m, b)
}
func (m *CheckObjectCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckObjectCountRequest.Marshal(b, m, deterministic)
}
func (m *CheckObjectCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckObjectCountRequest.Merge(m, src)
}
func (m *CheckObjectCountRequest) XXX_Size() int {
	return xxx_messageInfo_CheckObjectCountRequest.Size(m)
}
func (m *CheckObjectCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckObjectCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckObjectCountRequest proto.InternalMessageInfo

type CheckObjectCountReply struct {
	ListOfCounts         []*CountPerDb `protobuf:"bytes,1,rep,name=ListOfCounts,proto3" json:"ListOfCounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *CheckObjectCountReply) Reset()         { *m = CheckObjectCountReply{} }
func (m *CheckObjectCountReply) String() string { return proto.CompactTextString(m) }
func (*CheckObjectCountReply) ProtoMessage()    {}
func (*CheckObjectCountReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{11}
}

func (m *CheckObjectCountReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckObjectCountReply.Unmarshal(m, b)
}
func (m *CheckObjectCountReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckObjectCountReply.Marshal(b, m, deterministic)
}
func (m *CheckObjectCountReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckObjectCountReply.Merge(m, src)
}
func (m *CheckObjectCountReply) XXX_Size() int {
	return xxx_messageInfo_CheckObjectCountReply.Size(m)
}
func (m *CheckObjectCountReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckObjectCountReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckObjectCountReply proto.InternalMessageInfo

func (m *CheckObjectCountReply) GetListOfCounts() []*CountPerDb {
	if m != nil {
		return m.ListOfCounts
	}
	return nil
}

type CheckVersionRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVersionRequest) Reset()         { *m = CheckVersionRequest{} }
func (m *CheckVersionRequest) String() string { return proto.CompactTextString(m) }
func (*CheckVersionRequest) ProtoMessage()    {}
func (*CheckVersionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{12}
}

func (m *CheckVersionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionRequest.Unmarshal(m, b)
}
func (m *CheckVersionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionRequest.Marshal(b, m, deterministic)
}
func (m *CheckVersionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionRequest.Merge(m, src)
}
func (m *CheckVersionRequest) XXX_Size() int {
	return xxx_messageInfo_CheckVersionRequest.Size(m)
}
func (m *CheckVersionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionRequest proto.InternalMessageInfo

type CheckVersionReply struct {
	IsVersionCompatible  bool     `protobuf:"varint,1,opt,name=IsVersionCompatible,proto3" json:"IsVersionCompatible,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckVersionReply) Reset()         { *m = CheckVersionReply{} }
func (m *CheckVersionReply) String() string { return proto.CompactTextString(m) }
func (*CheckVersionReply) ProtoMessage()    {}
func (*CheckVersionReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{13}
}

func (m *CheckVersionReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckVersionReply.Unmarshal(m, b)
}
func (m *CheckVersionReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckVersionReply.Marshal(b, m, deterministic)
}
func (m *CheckVersionReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckVersionReply.Merge(m, src)
}
func (m *CheckVersionReply) XXX_Size() int {
	return xxx_messageInfo_CheckVersionReply.Size(m)
}
func (m *CheckVersionReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckVersionReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckVersionReply proto.InternalMessageInfo

func (m *CheckVersionReply) GetIsVersionCompatible() bool {
	if m != nil {
		return m.IsVersionCompatible
	}
	return false
}

type CheckDiskSpaceRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckDiskSpaceRequest) Reset()         { *m = CheckDiskSpaceRequest{} }
func (m *CheckDiskSpaceRequest) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceRequest) ProtoMessage()    {}
func (*CheckDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{14}
}

func (m *CheckDiskSpaceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceRequest.Unmarshal(m, b)
}
func (m *CheckDiskSpaceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceRequest.Marshal(b, m, deterministic)
}
func (m *CheckDiskSpaceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceRequest.Merge(m, src)
}
func (m *CheckDiskSpaceRequest) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceRequest.Size(m)
}
func (m *CheckDiskSpaceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceRequest proto.InternalMessageInfo

type CheckDiskSpaceReply struct {
	SegmentFileSysUsage  []string `protobuf:"bytes,1,rep,name=SegmentFileSysUsage,proto3" json:"SegmentFileSysUsage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckDiskSpaceReply) Reset()         { *m = CheckDiskSpaceReply{} }
func (m *CheckDiskSpaceReply) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceReply) ProtoMessage()    {}
func (*CheckDiskSpaceReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{15}
}

func (m *CheckDiskSpaceReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceReply.Unmarshal(m, b)
}
func (m *CheckDiskSpaceReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceReply.Marshal(b, m, deterministic)
}
func (m *CheckDiskSpaceReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceReply.Merge(m, src)
}
func (m *CheckDiskSpaceReply) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceReply.Size(m)
}
func (m *CheckDiskSpaceReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceReply.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceReply proto.InternalMessageInfo

func (m *CheckDiskSpaceReply) GetSegmentFileSysUsage() []string {
	if m != nil {
		return m.SegmentFileSysUsage
	}
	return nil
}

type PrepareInitClusterRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareInitClusterRequest) Reset()         { *m = PrepareInitClusterRequest{} }
func (m *PrepareInitClusterRequest) String() string { return proto.CompactTextString(m) }
func (*PrepareInitClusterRequest) ProtoMessage()    {}
func (*PrepareInitClusterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{16}
}

func (m *PrepareInitClusterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareInitClusterRequest.Unmarshal(m, b)
}
func (m *PrepareInitClusterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareInitClusterRequest.Marshal(b, m, deterministic)
}
func (m *PrepareInitClusterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareInitClusterRequest.Merge(m, src)
}
func (m *PrepareInitClusterRequest) XXX_Size() int {
	return xxx_messageInfo_PrepareInitClusterRequest.Size(m)
}
func (m *PrepareInitClusterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareInitClusterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareInitClusterRequest proto.InternalMessageInfo

type PrepareInitClusterReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PrepareInitClusterReply) Reset()         { *m = PrepareInitClusterReply{} }
func (m *PrepareInitClusterReply) String() string { return proto.CompactTextString(m) }
func (*PrepareInitClusterReply) ProtoMessage()    {}
func (*PrepareInitClusterReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{17}
}

func (m *PrepareInitClusterReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PrepareInitClusterReply.Unmarshal(m, b)
}
func (m *PrepareInitClusterReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PrepareInitClusterReply.Marshal(b, m, deterministic)
}
func (m *PrepareInitClusterReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepareInitClusterReply.Merge(m, src)
}
func (m *PrepareInitClusterReply) XXX_Size() int {
	return xxx_messageInfo_PrepareInitClusterReply.Size(m)
}
func (m *PrepareInitClusterReply) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepareInitClusterReply.DiscardUnknown(m)
}

var xxx_messageInfo_PrepareInitClusterReply proto.InternalMessageInfo

type Chunk struct {
	Buffer               []byte     `protobuf:"bytes,1,opt,name=buffer,proto3" json:"buffer,omitempty"`
	Type                 Chunk_Type `protobuf:"varint,2,opt,name=type,proto3,enum=idl.Chunk_Type" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Chunk) Reset()         { *m = Chunk{} }
func (m *Chunk) String() string { return proto.CompactTextString(m) }
func (*Chunk) ProtoMessage()    {}
func (*Chunk) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{18}
}

func (m *Chunk) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Chunk.Unmarshal(m, b)
}
func (m *Chunk) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Chunk.Marshal(b, m, deterministic)
}
func (m *Chunk) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Chunk.Merge(m, src)
}
func (m *Chunk) XXX_Size() int {
	return xxx_messageInfo_Chunk.Size(m)
}
func (m *Chunk) XXX_DiscardUnknown() {
	xxx_messageInfo_Chunk.DiscardUnknown(m)
}

var xxx_messageInfo_Chunk proto.InternalMessageInfo

func (m *Chunk) GetBuffer() []byte {
	if m != nil {
		return m.Buffer
	}
	return nil
}

func (m *Chunk) GetType() Chunk_Type {
	if m != nil {
		return m.Type
	}
	return Chunk_UNKNOWN
}

type Message struct {
	// Types that are valid to be assigned to Contents:
	//	*Message_Chunk
	//	*Message_Status
	Contents             isMessage_Contents `protobuf_oneof:"contents"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{19}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

type isMessage_Contents interface {
	isMessage_Contents()
}

type Message_Chunk struct {
	Chunk *Chunk `protobuf:"bytes,1,opt,name=chunk,proto3,oneof"`
}

type Message_Status struct {
	Status *UpgradeStepStatus `protobuf:"bytes,2,opt,name=status,proto3,oneof"`
}

func (*Message_Chunk) isMessage_Contents() {}

func (*Message_Status) isMessage_Contents() {}

func (m *Message) GetContents() isMessage_Contents {
	if m != nil {
		return m.Contents
	}
	return nil
}

func (m *Message) GetChunk() *Chunk {
	if x, ok := m.GetContents().(*Message_Chunk); ok {
		return x.Chunk
	}
	return nil
}

func (m *Message) GetStatus() *UpgradeStepStatus {
	if x, ok := m.GetContents().(*Message_Status); ok {
		return x.Status
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Message) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Message_Chunk)(nil),
		(*Message_Status)(nil),
	}
}

type SetConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigRequest) Reset()         { *m = SetConfigRequest{} }
func (m *SetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*SetConfigRequest) ProtoMessage()    {}
func (*SetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{20}
}

func (m *SetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigRequest.Unmarshal(m, b)
}
func (m *SetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigRequest.Marshal(b, m, deterministic)
}
func (m *SetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigRequest.Merge(m, src)
}
func (m *SetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_SetConfigRequest.Size(m)
}
func (m *SetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigRequest proto.InternalMessageInfo

func (m *SetConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SetConfigRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SetConfigReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetConfigReply) Reset()         { *m = SetConfigReply{} }
func (m *SetConfigReply) String() string { return proto.CompactTextString(m) }
func (*SetConfigReply) ProtoMessage()    {}
func (*SetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{21}
}

func (m *SetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetConfigReply.Unmarshal(m, b)
}
func (m *SetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetConfigReply.Marshal(b, m, deterministic)
}
func (m *SetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetConfigReply.Merge(m, src)
}
func (m *SetConfigReply) XXX_Size() int {
	return xxx_messageInfo_SetConfigReply.Size(m)
}
func (m *SetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_SetConfigReply proto.InternalMessageInfo

type GetConfigRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigRequest) Reset()         { *m = GetConfigRequest{} }
func (m *GetConfigRequest) String() string { return proto.CompactTextString(m) }
func (*GetConfigRequest) ProtoMessage()    {}
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{22}
}

func (m *GetConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigRequest.Unmarshal(m, b)
}
func (m *GetConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigRequest.Marshal(b, m, deterministic)
}
func (m *GetConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigRequest.Merge(m, src)
}
func (m *GetConfigRequest) XXX_Size() int {
	return xxx_messageInfo_GetConfigRequest.Size(m)
}
func (m *GetConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigRequest proto.InternalMessageInfo

func (m *GetConfigRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetConfigReply struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetConfigReply) Reset()         { *m = GetConfigReply{} }
func (m *GetConfigReply) String() string { return proto.CompactTextString(m) }
func (*GetConfigReply) ProtoMessage()    {}
func (*GetConfigReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_631e66a01873be02, []int{23}
}

func (m *GetConfigReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetConfigReply.Unmarshal(m, b)
}
func (m *GetConfigReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetConfigReply.Marshal(b, m, deterministic)
}
func (m *GetConfigReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetConfigReply.Merge(m, src)
}
func (m *GetConfigReply) XXX_Size() int {
	return xxx_messageInfo_GetConfigReply.Size(m)
}
func (m *GetConfigReply) XXX_DiscardUnknown() {
	xxx_messageInfo_GetConfigReply.DiscardUnknown(m)
}

var xxx_messageInfo_GetConfigReply proto.InternalMessageInfo

func (m *GetConfigReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterEnum("idl.UpgradeSteps", UpgradeSteps_name, UpgradeSteps_value)
	proto.RegisterEnum("idl.StepStatus", StepStatus_name, StepStatus_value)
	proto.RegisterEnum("idl.Chunk_Type", Chunk_Type_name, Chunk_Type_value)
	proto.RegisterType((*InitializeRequest)(nil), "idl.InitializeRequest")
	proto.RegisterType((*InitializeCreateClusterRequest)(nil), "idl.InitializeCreateClusterRequest")
	proto.RegisterType((*ExecuteRequest)(nil), "idl.ExecuteRequest")
	proto.RegisterType((*FinalizeRequest)(nil), "idl.FinalizeRequest")
	proto.RegisterType((*RestartAgentsRequest)(nil), "idl.RestartAgentsRequest")
	proto.RegisterType((*RestartAgentsReply)(nil), "idl.RestartAgentsReply")
	proto.RegisterType((*StopServicesRequest)(nil), "idl.StopServicesRequest")
	proto.RegisterType((*StopServicesReply)(nil), "idl.StopServicesReply")
	proto.RegisterType((*UpgradeStepStatus)(nil), "idl.UpgradeStepStatus")
	proto.RegisterType((*CountPerDb)(nil), "idl.CountPerDb")
	proto.RegisterType((*CheckObjectCountRequest)(nil), "idl.CheckObjectCountRequest")
	proto.RegisterType((*CheckObjectCountReply)(nil), "idl.CheckObjectCountReply")
	proto.RegisterType((*CheckVersionRequest)(nil), "idl.CheckVersionRequest")
	proto.RegisterType((*CheckVersionReply)(nil), "idl.CheckVersionReply")
	proto.RegisterType((*CheckDiskSpaceRequest)(nil), "idl.CheckDiskSpaceRequest")
	proto.RegisterType((*CheckDiskSpaceReply)(nil), "idl.CheckDiskSpaceReply")
	proto.RegisterType((*PrepareInitClusterRequest)(nil), "idl.PrepareInitClusterRequest")
	proto.RegisterType((*PrepareInitClusterReply)(nil), "idl.PrepareInitClusterReply")
	proto.RegisterType((*Chunk)(nil), "idl.Chunk")
	proto.RegisterType((*Message)(nil), "idl.Message")
	proto.RegisterType((*SetConfigRequest)(nil), "idl.SetConfigRequest")
	proto.RegisterType((*SetConfigReply)(nil), "idl.SetConfigReply")
	proto.RegisterType((*GetConfigRequest)(nil), "idl.GetConfigRequest")
	proto.RegisterType((*GetConfigReply)(nil), "idl.GetConfigReply")
}

func init() { proto.RegisterFile("cli_to_hub.proto", fileDescriptor_631e66a01873be02) }

var fileDescriptor_631e66a01873be02 = []byte{
	// 1046 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x7f, 0x6f, 0xe2, 0x46,
	0x10, 0x85, 0x04, 0x02, 0x0c, 0x1c, 0x31, 0x4b, 0x12, 0x08, 0x77, 0x3a, 0x45, 0x3e, 0xf5, 0x1a,
	0x5d, 0xa5, 0x28, 0xe2, 0xaa, 0x4a, 0x27, 0xf5, 0x1f, 0x62, 0x1c, 0x40, 0x97, 0x18, 0x6b, 0x6d,
	0x5a, 0x55, 0xaa, 0x84, 0x0c, 0xd9, 0x24, 0x6e, 0x1c, 0xdb, 0x67, 0x2f, 0xd7, 0xd2, 0xaf, 0xd6,
	0x4f, 0xd2, 0x6f, 0x53, 0xed, 0x7a, 0x8d, 0x7f, 0xc4, 0x27, 0xf5, 0x3f, 0xef, 0x7b, 0x3b, 0x6f,
	0xd6, 0xe3, 0xb7, 0x33, 0x06, 0x69, 0xed, 0xd8, 0x4b, 0xea, 0x2d, 0x1f, 0x37, 0xab, 0x0b, 0x3f,
	0xf0, 0xa8, 0x87, 0xf6, 0xed, 0x3b, 0x47, 0xb6, 0xa1, 0x33, 0x73, 0x6d, 0x6a, 0x5b, 0x8e, 0xfd,
	0x37, 0xc1, 0xe4, 0xcb, 0x86, 0x84, 0x14, 0xbd, 0x81, 0x86, 0xe7, 0xdc, 0x5d, 0xd9, 0xee, 0xd8,
	0x0e, 0xfa, 0xe5, 0xb3, 0xf2, 0x79, 0x03, 0x27, 0x00, 0x63, 0x5d, 0xf2, 0xa7, 0x60, 0xf7, 0x22,
	0x76, 0x07, 0xa0, 0x3e, 0xd4, 0x3c, 0xe7, 0x4e, 0xf7, 0x02, 0xda, 0xdf, 0x3f, 0x2b, 0x9f, 0x57,
	0x71, 0xbc, 0x94, 0xcf, 0xe0, 0x6d, 0x92, 0x4a, 0x09, 0x88, 0x45, 0x89, 0xe2, 0x6c, 0x42, 0x4a,
	0x02, 0x91, 0x57, 0x96, 0xa0, 0xad, 0xfe, 0x45, 0xd6, 0x1b, 0x1a, 0x9f, 0x44, 0xee, 0xc0, 0xe1,
	0xb5, 0xed, 0xa6, 0x0f, 0x27, 0x9f, 0xc0, 0x11, 0x26, 0x21, 0xb5, 0x02, 0x3a, 0x7a, 0x20, 0x2e,
	0x0d, 0x63, 0xfc, 0x47, 0x40, 0x39, 0xdc, 0x77, 0xb6, 0xe8, 0x2d, 0x80, 0xc5, 0x96, 0x53, 0x2f,
	0xa4, 0x61, 0xbf, 0x7c, 0xb6, 0x7f, 0xde, 0xc0, 0x29, 0x44, 0x3e, 0x86, 0xae, 0x41, 0x3d, 0xdf,
	0x20, 0xc1, 0x57, 0x7b, 0x4d, 0x76, 0x62, 0x5d, 0xe8, 0x64, 0x61, 0xdf, 0xd9, 0xca, 0x6b, 0xe8,
	0x2c, 0xfc, 0x87, 0xc0, 0xba, 0x23, 0x06, 0x25, 0xbe, 0x41, 0x2d, 0xba, 0x09, 0xd1, 0x77, 0x50,
	0x09, 0x29, 0xf1, 0x79, 0x99, 0xda, 0xc3, 0xce, 0x85, 0x7d, 0xe7, 0x5c, 0xa4, 0x76, 0x85, 0x98,
	0xd3, 0xe8, 0x7b, 0x38, 0x08, 0x79, 0x00, 0xaf, 0x58, 0x7b, 0x78, 0xc8, 0x37, 0x26, 0x3a, 0x58,
	0xd0, 0xf2, 0xef, 0x00, 0x8a, 0xb7, 0x71, 0xa9, 0x4e, 0x82, 0xf1, 0x0a, 0x9d, 0xc0, 0xc1, 0x78,
	0xa5, 0x59, 0xcf, 0x44, 0x7c, 0x06, 0xb1, 0x62, 0x55, 0x1e, 0x79, 0x7c, 0x1f, 0xd7, 0xab, 0xe2,
	0x78, 0xc9, 0xbe, 0xce, 0x94, 0x58, 0x7e, 0xc4, 0x45, 0x5f, 0x20, 0x01, 0xe4, 0x53, 0xe8, 0x29,
	0x8f, 0x64, 0xfd, 0x34, 0x5f, 0xfd, 0x41, 0xd6, 0x94, 0x63, 0xf1, 0x2b, 0xdf, 0xc0, 0xf1, 0x4b,
	0x8a, 0x95, 0xf0, 0x23, 0xb4, 0x6e, 0xec, 0x90, 0xce, 0xef, 0x39, 0x16, 0x15, 0xb1, 0x29, 0x5e,
	0x20, 0x39, 0x2a, 0xce, 0x6c, 0x62, 0x75, 0xe5, 0x6a, 0xbf, 0x90, 0x20, 0xb4, 0x3d, 0x37, 0x4e,
	0xa2, 0x42, 0x27, 0x0b, 0xb3, 0x04, 0x97, 0xd0, 0x9d, 0x85, 0x02, 0x51, 0xbc, 0x67, 0xdf, 0xa2,
	0xf6, 0xca, 0x89, 0xde, 0xb8, 0x8e, 0x8b, 0x28, 0xb9, 0x27, 0xce, 0x3a, 0xb6, 0xc3, 0x27, 0xc3,
	0xb7, 0xd6, 0x3b, 0x73, 0x4c, 0x44, 0xda, 0x14, 0x21, 0x32, 0x18, 0xe4, 0xe1, 0x99, 0xb8, 0xf4,
	0xda, 0x76, 0x88, 0xb1, 0x0d, 0x17, 0xa1, 0xf5, 0x40, 0x84, 0x1d, 0x8a, 0x28, 0xf9, 0x35, 0x9c,
	0xea, 0x01, 0xf1, 0xad, 0x80, 0x30, 0xcf, 0xe6, 0x7c, 0x7a, 0x0a, 0xbd, 0x22, 0x92, 0x79, 0xe4,
	0x0b, 0x54, 0x95, 0xc7, 0x8d, 0xfb, 0xc4, 0xbe, 0xdc, 0x6a, 0x73, 0x7f, 0x4f, 0xa2, 0x0b, 0xd4,
	0xc2, 0x62, 0x85, 0xde, 0x41, 0x85, 0x6e, 0x7d, 0x92, 0xb1, 0x01, 0x8f, 0xb8, 0x30, 0xb7, 0x3e,
	0xc1, 0x9c, 0x94, 0x7f, 0x80, 0x0a, 0x5b, 0xa1, 0x26, 0xd4, 0x16, 0xda, 0x67, 0x6d, 0xfe, 0xab,
	0x26, 0x95, 0x10, 0xc0, 0x81, 0x61, 0x8e, 0xe7, 0x0b, 0x53, 0x2a, 0x8b, 0x67, 0x15, 0x63, 0x69,
	0x4f, 0x7e, 0x82, 0xda, 0x2d, 0x09, 0xd9, 0xa9, 0x91, 0x0c, 0xd5, 0x35, 0xd3, 0xe2, 0x39, 0x9b,
	0x43, 0x48, 0xd4, 0xa7, 0x25, 0x1c, 0x51, 0xe8, 0x32, 0xe3, 0xc4, 0xe6, 0xf0, 0x24, 0x6f, 0xd9,
	0xc8, 0x90, 0xd3, 0x52, 0x6c, 0xc9, 0x2b, 0x80, 0xfa, 0xda, 0x73, 0x29, 0xbb, 0x54, 0xf2, 0xcf,
	0x20, 0x19, 0x84, 0x2a, 0x9e, 0x7b, 0x6f, 0x3f, 0xc4, 0xed, 0x02, 0x41, 0xc5, 0x4d, 0x2c, 0xca,
	0x9f, 0xd1, 0x11, 0x54, 0xbf, 0x5a, 0xce, 0x86, 0x88, 0x06, 0x11, 0x2d, 0xd8, 0x05, 0x4f, 0x45,
	0xb3, 0x7a, 0xbd, 0x07, 0x69, 0xf2, 0x3f, 0xf4, 0xe4, 0xf7, 0xd0, 0x9e, 0x64, 0x22, 0x93, 0x0c,
	0xe5, 0x54, 0x86, 0x0f, 0xff, 0xec, 0x41, 0x2b, 0x7d, 0xfd, 0x90, 0x04, 0x2d, 0x51, 0xc2, 0xa5,
	0x61, 0xaa, 0x7a, 0x54, 0x47, 0x65, 0xae, 0x5d, 0xcf, 0x26, 0x52, 0x99, 0xb1, 0x86, 0x39, 0xc2,
	0xe6, 0x72, 0x34, 0x51, 0x35, 0xd3, 0x90, 0xf6, 0x50, 0x0f, 0xba, 0x33, 0x6d, 0x66, 0x2e, 0xcd,
	0x11, 0x9e, 0xa8, 0xe6, 0x52, 0xb9, 0x59, 0x18, 0xa6, 0x8a, 0xa5, 0x7d, 0xf4, 0x1a, 0x7a, 0xc6,
	0x74, 0x61, 0x8e, 0x99, 0x52, 0x8e, 0xac, 0x30, 0x1d, 0x65, 0xaa, 0x2a, 0x9f, 0x97, 0xb7, 0x23,
	0x8e, 0x54, 0x51, 0x17, 0x0e, 0x23, 0x44, 0xc7, 0xb3, 0xdb, 0x11, 0x9e, 0xa9, 0x86, 0x74, 0x80,
	0x06, 0x70, 0x82, 0xd5, 0x28, 0x61, 0x4e, 0xa2, 0x86, 0x8e, 0xa1, 0xb3, 0xd3, 0x17, 0xa8, 0x21,
	0xd5, 0x11, 0x82, 0xf6, 0x42, 0x9f, 0xe0, 0xd1, 0x58, 0x8d, 0xb5, 0x1b, 0xe8, 0x10, 0x9a, 0xca,
	0x5c, 0xff, 0x2d, 0x06, 0x80, 0xc5, 0xc6, 0x9b, 0x92, 0x74, 0x4d, 0xd4, 0x87, 0xa3, 0xc2, 0x64,
	0x2d, 0x16, 0x80, 0xd5, 0xa8, 0x0a, 0x0b, 0xac, 0x2e, 0xf5, 0x39, 0x36, 0x0d, 0xe9, 0xd5, 0x07,
	0x13, 0x20, 0xd5, 0xda, 0x58, 0xea, 0x5d, 0xe9, 0x46, 0xe6, 0xc2, 0x90, 0x4a, 0xcc, 0x91, 0xba,
	0xaa, 0x8d, 0x67, 0x1a, 0xab, 0x5e, 0x13, 0x6a, 0x78, 0xa1, 0x69, 0x6c, 0xb1, 0x87, 0x5a, 0x50,
	0x57, 0xe6, 0xb7, 0xfa, 0x8d, 0x6a, 0xaa, 0xd2, 0x3e, 0x2b, 0xf2, 0xf5, 0x68, 0x76, 0xa3, 0x8e,
	0xa5, 0xca, 0xf0, 0xdf, 0x2a, 0xd4, 0x15, 0xc7, 0x36, 0xbd, 0xe9, 0x66, 0x85, 0x34, 0x90, 0xf2,
	0x6d, 0x06, 0xbd, 0x11, 0x3e, 0x2d, 0x6c, 0x4c, 0x83, 0xc1, 0x37, 0x58, 0x66, 0x9f, 0x12, 0xba,
	0x82, 0x56, 0xba, 0xa3, 0xa0, 0x7e, 0xb2, 0x3b, 0xdb, 0x7b, 0x06, 0x27, 0x05, 0x4c, 0xa4, 0x31,
	0x85, 0x76, 0xb6, 0x6b, 0xa0, 0x54, 0xce, 0x7c, 0x8f, 0x19, 0xf4, 0x0b, 0xb9, 0x48, 0xe9, 0x27,
	0x80, 0x64, 0xc6, 0xa1, 0x28, 0xe3, 0x8b, 0xf9, 0x3a, 0x68, 0x71, 0x5c, 0x5c, 0x5a, 0xb9, 0x74,
	0x59, 0x46, 0x3a, 0xf4, 0xbe, 0x31, 0x1b, 0xd1, 0xbb, 0x9c, 0x48, 0xd1, 0xe4, 0x2c, 0x50, 0xbc,
	0x84, 0x9a, 0x98, 0xa5, 0xa8, 0xcb, 0xc9, 0xec, 0x64, 0x2d, 0x88, 0x18, 0x42, 0x3d, 0x9e, 0xb5,
	0xe8, 0x88, 0xb3, 0xb9, 0xd1, 0x5b, 0x10, 0xf3, 0x09, 0x1a, 0xbb, 0x0b, 0x8d, 0x8e, 0xa3, 0x99,
	0x96, 0xbb, 0xce, 0x83, 0x6e, 0x1e, 0x8e, 0x4a, 0xf5, 0x09, 0x1a, 0x93, 0x5c, 0xe8, 0xa4, 0x38,
	0x74, 0x92, 0x0f, 0x55, 0xe1, 0x55, 0x66, 0xd4, 0xa3, 0x53, 0xbe, 0xaf, 0xe8, 0xb7, 0x60, 0xd0,
	0x2b, 0xa2, 0x76, 0xd6, 0x49, 0x0f, 0x79, 0x61, 0x9d, 0x82, 0xdf, 0x01, 0x61, 0x9d, 0x97, 0x7f,
	0x04, 0xa5, 0xd5, 0x01, 0xff, 0x97, 0xfa, 0xf8, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7a, 0x52,
	0x8f, 0xeb, 0x5f, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CliToHubClient is the client API for CliToHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CliToHubClient interface {
	CheckObjectCount(ctx context.Context, in *CheckObjectCountRequest, opts ...grpc.CallOption) (*CheckObjectCountReply, error)
	CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionReply, error)
	CheckDiskSpace(ctx context.Context, in *CheckDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error)
	Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (CliToHub_InitializeClient, error)
	InitializeCreateCluster(ctx context.Context, in *InitializeCreateClusterRequest, opts ...grpc.CallOption) (CliToHub_InitializeCreateClusterClient, error)
	Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (CliToHub_ExecuteClient, error)
	Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (CliToHub_FinalizeClient, error)
	SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigReply, error)
	GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error)
	RestartAgents(ctx context.Context, in *RestartAgentsRequest, opts ...grpc.CallOption) (*RestartAgentsReply, error)
	StopServices(ctx context.Context, in *StopServicesRequest, opts ...grpc.CallOption) (*StopServicesReply, error)
}

type cliToHubClient struct {
	cc *grpc.ClientConn
}

func NewCliToHubClient(cc *grpc.ClientConn) CliToHubClient {
	return &cliToHubClient{cc}
}

func (c *cliToHubClient) CheckObjectCount(ctx context.Context, in *CheckObjectCountRequest, opts ...grpc.CallOption) (*CheckObjectCountReply, error) {
	out := new(CheckObjectCountReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/CheckObjectCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) CheckVersion(ctx context.Context, in *CheckVersionRequest, opts ...grpc.CallOption) (*CheckVersionReply, error) {
	out := new(CheckVersionReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/CheckVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) CheckDiskSpace(ctx context.Context, in *CheckDiskSpaceRequest, opts ...grpc.CallOption) (*CheckDiskSpaceReply, error) {
	out := new(CheckDiskSpaceReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/CheckDiskSpace", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) Initialize(ctx context.Context, in *InitializeRequest, opts ...grpc.CallOption) (CliToHub_InitializeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[0], "/idl.CliToHub/Initialize", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubInitializeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_InitializeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubInitializeClient struct {
	grpc.ClientStream
}

func (x *cliToHubInitializeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) InitializeCreateCluster(ctx context.Context, in *InitializeCreateClusterRequest, opts ...grpc.CallOption) (CliToHub_InitializeCreateClusterClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[1], "/idl.CliToHub/InitializeCreateCluster", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubInitializeCreateClusterClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_InitializeCreateClusterClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubInitializeCreateClusterClient struct {
	grpc.ClientStream
}

func (x *cliToHubInitializeCreateClusterClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Execute(ctx context.Context, in *ExecuteRequest, opts ...grpc.CallOption) (CliToHub_ExecuteClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[2], "/idl.CliToHub/Execute", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubExecuteClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_ExecuteClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubExecuteClient struct {
	grpc.ClientStream
}

func (x *cliToHubExecuteClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) Finalize(ctx context.Context, in *FinalizeRequest, opts ...grpc.CallOption) (CliToHub_FinalizeClient, error) {
	stream, err := c.cc.NewStream(ctx, &_CliToHub_serviceDesc.Streams[3], "/idl.CliToHub/Finalize", opts...)
	if err != nil {
		return nil, err
	}
	x := &cliToHubFinalizeClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type CliToHub_FinalizeClient interface {
	Recv() (*Message, error)
	grpc.ClientStream
}

type cliToHubFinalizeClient struct {
	grpc.ClientStream
}

func (x *cliToHubFinalizeClient) Recv() (*Message, error) {
	m := new(Message)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *cliToHubClient) SetConfig(ctx context.Context, in *SetConfigRequest, opts ...grpc.CallOption) (*SetConfigReply, error) {
	out := new(SetConfigReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/SetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) GetConfig(ctx context.Context, in *GetConfigRequest, opts ...grpc.CallOption) (*GetConfigReply, error) {
	out := new(GetConfigReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/GetConfig", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) RestartAgents(ctx context.Context, in *RestartAgentsRequest, opts ...grpc.CallOption) (*RestartAgentsReply, error) {
	out := new(RestartAgentsReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/RestartAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cliToHubClient) StopServices(ctx context.Context, in *StopServicesRequest, opts ...grpc.CallOption) (*StopServicesReply, error) {
	out := new(StopServicesReply)
	err := c.cc.Invoke(ctx, "/idl.CliToHub/StopServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CliToHubServer is the server API for CliToHub service.
type CliToHubServer interface {
	CheckObjectCount(context.Context, *CheckObjectCountRequest) (*CheckObjectCountReply, error)
	CheckVersion(context.Context, *CheckVersionRequest) (*CheckVersionReply, error)
	CheckDiskSpace(context.Context, *CheckDiskSpaceRequest) (*CheckDiskSpaceReply, error)
	Initialize(*InitializeRequest, CliToHub_InitializeServer) error
	InitializeCreateCluster(*InitializeCreateClusterRequest, CliToHub_InitializeCreateClusterServer) error
	Execute(*ExecuteRequest, CliToHub_ExecuteServer) error
	Finalize(*FinalizeRequest, CliToHub_FinalizeServer) error
	SetConfig(context.Context, *SetConfigRequest) (*SetConfigReply, error)
	GetConfig(context.Context, *GetConfigRequest) (*GetConfigReply, error)
	RestartAgents(context.Context, *RestartAgentsRequest) (*RestartAgentsReply, error)
	StopServices(context.Context, *StopServicesRequest) (*StopServicesReply, error)
}

// UnimplementedCliToHubServer can be embedded to have forward compatible implementations.
type UnimplementedCliToHubServer struct {
}

func (*UnimplementedCliToHubServer) CheckObjectCount(ctx context.Context, req *CheckObjectCountRequest) (*CheckObjectCountReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckObjectCount not implemented")
}
func (*UnimplementedCliToHubServer) CheckVersion(ctx context.Context, req *CheckVersionRequest) (*CheckVersionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckVersion not implemented")
}
func (*UnimplementedCliToHubServer) CheckDiskSpace(ctx context.Context, req *CheckDiskSpaceRequest) (*CheckDiskSpaceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDiskSpace not implemented")
}
func (*UnimplementedCliToHubServer) Initialize(req *InitializeRequest, srv CliToHub_InitializeServer) error {
	return status.Errorf(codes.Unimplemented, "method Initialize not implemented")
}
func (*UnimplementedCliToHubServer) InitializeCreateCluster(req *InitializeCreateClusterRequest, srv CliToHub_InitializeCreateClusterServer) error {
	return status.Errorf(codes.Unimplemented, "method InitializeCreateCluster not implemented")
}
func (*UnimplementedCliToHubServer) Execute(req *ExecuteRequest, srv CliToHub_ExecuteServer) error {
	return status.Errorf(codes.Unimplemented, "method Execute not implemented")
}
func (*UnimplementedCliToHubServer) Finalize(req *FinalizeRequest, srv CliToHub_FinalizeServer) error {
	return status.Errorf(codes.Unimplemented, "method Finalize not implemented")
}
func (*UnimplementedCliToHubServer) SetConfig(ctx context.Context, req *SetConfigRequest) (*SetConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetConfig not implemented")
}
func (*UnimplementedCliToHubServer) GetConfig(ctx context.Context, req *GetConfigRequest) (*GetConfigReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetConfig not implemented")
}
func (*UnimplementedCliToHubServer) RestartAgents(ctx context.Context, req *RestartAgentsRequest) (*RestartAgentsReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestartAgents not implemented")
}
func (*UnimplementedCliToHubServer) StopServices(ctx context.Context, req *StopServicesRequest) (*StopServicesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopServices not implemented")
}

func RegisterCliToHubServer(s *grpc.Server, srv CliToHubServer) {
	s.RegisterService(&_CliToHub_serviceDesc, srv)
}

func _CliToHub_CheckObjectCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckObjectCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckObjectCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckObjectCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckObjectCount(ctx, req.(*CheckObjectCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_CheckVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckVersion(ctx, req.(*CheckVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_CheckDiskSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDiskSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).CheckDiskSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/CheckDiskSpace",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).CheckDiskSpace(ctx, req.(*CheckDiskSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_Initialize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitializeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Initialize(m, &cliToHubInitializeServer{stream})
}

type CliToHub_InitializeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubInitializeServer struct {
	grpc.ServerStream
}

func (x *cliToHubInitializeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_InitializeCreateCluster_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(InitializeCreateClusterRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).InitializeCreateCluster(m, &cliToHubInitializeCreateClusterServer{stream})
}

type CliToHub_InitializeCreateClusterServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubInitializeCreateClusterServer struct {
	grpc.ServerStream
}

func (x *cliToHubInitializeCreateClusterServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Execute(m, &cliToHubExecuteServer{stream})
}

type CliToHub_ExecuteServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubExecuteServer struct {
	grpc.ServerStream
}

func (x *cliToHubExecuteServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_Finalize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FinalizeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CliToHubServer).Finalize(m, &cliToHubFinalizeServer{stream})
}

type CliToHub_FinalizeServer interface {
	Send(*Message) error
	grpc.ServerStream
}

type cliToHubFinalizeServer struct {
	grpc.ServerStream
}

func (x *cliToHubFinalizeServer) Send(m *Message) error {
	return x.ServerStream.SendMsg(m)
}

func _CliToHub_SetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).SetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/SetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).SetConfig(ctx, req.(*SetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_GetConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).GetConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/GetConfig",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).GetConfig(ctx, req.(*GetConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_RestartAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestartAgentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).RestartAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/RestartAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).RestartAgents(ctx, req.(*RestartAgentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CliToHub_StopServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CliToHubServer).StopServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.CliToHub/StopServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CliToHubServer).StopServices(ctx, req.(*StopServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CliToHub_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.CliToHub",
	HandlerType: (*CliToHubServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckObjectCount",
			Handler:    _CliToHub_CheckObjectCount_Handler,
		},
		{
			MethodName: "CheckVersion",
			Handler:    _CliToHub_CheckVersion_Handler,
		},
		{
			MethodName: "CheckDiskSpace",
			Handler:    _CliToHub_CheckDiskSpace_Handler,
		},
		{
			MethodName: "SetConfig",
			Handler:    _CliToHub_SetConfig_Handler,
		},
		{
			MethodName: "GetConfig",
			Handler:    _CliToHub_GetConfig_Handler,
		},
		{
			MethodName: "RestartAgents",
			Handler:    _CliToHub_RestartAgents_Handler,
		},
		{
			MethodName: "StopServices",
			Handler:    _CliToHub_StopServices_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Initialize",
			Handler:       _CliToHub_Initialize_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "InitializeCreateCluster",
			Handler:       _CliToHub_InitializeCreateCluster_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Execute",
			Handler:       _CliToHub_Execute_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "Finalize",
			Handler:       _CliToHub_Finalize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "cli_to_hub.proto",
}
