// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hub_to_agent.proto

package idl

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpgradePrimariesRequest struct {
	OldBinDir            string         `protobuf:"bytes,1,opt,name=OldBinDir,proto3" json:"OldBinDir,omitempty"`
	NewBinDir            string         `protobuf:"bytes,2,opt,name=NewBinDir,proto3" json:"NewBinDir,omitempty"`
	NewVersion           string         `protobuf:"bytes,3,opt,name=NewVersion,proto3" json:"NewVersion,omitempty"`
	DataDirPairs         []*DataDirPair `protobuf:"bytes,4,rep,name=DataDirPairs,proto3" json:"DataDirPairs,omitempty"`
	CheckOnly            bool           `protobuf:"varint,5,opt,name=CheckOnly,proto3" json:"CheckOnly,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *UpgradePrimariesRequest) Reset()         { *m = UpgradePrimariesRequest{} }
func (m *UpgradePrimariesRequest) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesRequest) ProtoMessage()    {}
func (*UpgradePrimariesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{0}
}

func (m *UpgradePrimariesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesRequest.Unmarshal(m, b)
}
func (m *UpgradePrimariesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesRequest.Marshal(b, m, deterministic)
}
func (m *UpgradePrimariesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesRequest.Merge(m, src)
}
func (m *UpgradePrimariesRequest) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesRequest.Size(m)
}
func (m *UpgradePrimariesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesRequest proto.InternalMessageInfo

func (m *UpgradePrimariesRequest) GetOldBinDir() string {
	if m != nil {
		return m.OldBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetNewBinDir() string {
	if m != nil {
		return m.NewBinDir
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetNewVersion() string {
	if m != nil {
		return m.NewVersion
	}
	return ""
}

func (m *UpgradePrimariesRequest) GetDataDirPairs() []*DataDirPair {
	if m != nil {
		return m.DataDirPairs
	}
	return nil
}

func (m *UpgradePrimariesRequest) GetCheckOnly() bool {
	if m != nil {
		return m.CheckOnly
	}
	return false
}

type DataDirPair struct {
	OldDataDir           string   `protobuf:"bytes,1,opt,name=OldDataDir,proto3" json:"OldDataDir,omitempty"`
	NewDataDir           string   `protobuf:"bytes,2,opt,name=NewDataDir,proto3" json:"NewDataDir,omitempty"`
	OldPort              int32    `protobuf:"varint,3,opt,name=OldPort,proto3" json:"OldPort,omitempty"`
	NewPort              int32    `protobuf:"varint,4,opt,name=NewPort,proto3" json:"NewPort,omitempty"`
	Content              int32    `protobuf:"varint,5,opt,name=Content,proto3" json:"Content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DataDirPair) Reset()         { *m = DataDirPair{} }
func (m *DataDirPair) String() string { return proto.CompactTextString(m) }
func (*DataDirPair) ProtoMessage()    {}
func (*DataDirPair) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{1}
}

func (m *DataDirPair) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DataDirPair.Unmarshal(m, b)
}
func (m *DataDirPair) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DataDirPair.Marshal(b, m, deterministic)
}
func (m *DataDirPair) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DataDirPair.Merge(m, src)
}
func (m *DataDirPair) XXX_Size() int {
	return xxx_messageInfo_DataDirPair.Size(m)
}
func (m *DataDirPair) XXX_DiscardUnknown() {
	xxx_messageInfo_DataDirPair.DiscardUnknown(m)
}

var xxx_messageInfo_DataDirPair proto.InternalMessageInfo

func (m *DataDirPair) GetOldDataDir() string {
	if m != nil {
		return m.OldDataDir
	}
	return ""
}

func (m *DataDirPair) GetNewDataDir() string {
	if m != nil {
		return m.NewDataDir
	}
	return ""
}

func (m *DataDirPair) GetOldPort() int32 {
	if m != nil {
		return m.OldPort
	}
	return 0
}

func (m *DataDirPair) GetNewPort() int32 {
	if m != nil {
		return m.NewPort
	}
	return 0
}

func (m *DataDirPair) GetContent() int32 {
	if m != nil {
		return m.Content
	}
	return 0
}

type UpgradePrimariesReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradePrimariesReply) Reset()         { *m = UpgradePrimariesReply{} }
func (m *UpgradePrimariesReply) String() string { return proto.CompactTextString(m) }
func (*UpgradePrimariesReply) ProtoMessage()    {}
func (*UpgradePrimariesReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{2}
}

func (m *UpgradePrimariesReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradePrimariesReply.Unmarshal(m, b)
}
func (m *UpgradePrimariesReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradePrimariesReply.Marshal(b, m, deterministic)
}
func (m *UpgradePrimariesReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradePrimariesReply.Merge(m, src)
}
func (m *UpgradePrimariesReply) XXX_Size() int {
	return xxx_messageInfo_UpgradePrimariesReply.Size(m)
}
func (m *UpgradePrimariesReply) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradePrimariesReply.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradePrimariesReply proto.InternalMessageInfo

type FileSysUsage struct {
	Filesystem           string   `protobuf:"bytes,1,opt,name=Filesystem,proto3" json:"Filesystem,omitempty"`
	Usage                float64  `protobuf:"fixed64,2,opt,name=Usage,proto3" json:"Usage,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FileSysUsage) Reset()         { *m = FileSysUsage{} }
func (m *FileSysUsage) String() string { return proto.CompactTextString(m) }
func (*FileSysUsage) ProtoMessage()    {}
func (*FileSysUsage) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{3}
}

func (m *FileSysUsage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FileSysUsage.Unmarshal(m, b)
}
func (m *FileSysUsage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FileSysUsage.Marshal(b, m, deterministic)
}
func (m *FileSysUsage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FileSysUsage.Merge(m, src)
}
func (m *FileSysUsage) XXX_Size() int {
	return xxx_messageInfo_FileSysUsage.Size(m)
}
func (m *FileSysUsage) XXX_DiscardUnknown() {
	xxx_messageInfo_FileSysUsage.DiscardUnknown(m)
}

var xxx_messageInfo_FileSysUsage proto.InternalMessageInfo

func (m *FileSysUsage) GetFilesystem() string {
	if m != nil {
		return m.Filesystem
	}
	return ""
}

func (m *FileSysUsage) GetUsage() float64 {
	if m != nil {
		return m.Usage
	}
	return 0
}

type CheckDiskSpaceRequestToAgent struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckDiskSpaceRequestToAgent) Reset()         { *m = CheckDiskSpaceRequestToAgent{} }
func (m *CheckDiskSpaceRequestToAgent) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceRequestToAgent) ProtoMessage()    {}
func (*CheckDiskSpaceRequestToAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{4}
}

func (m *CheckDiskSpaceRequestToAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceRequestToAgent.Unmarshal(m, b)
}
func (m *CheckDiskSpaceRequestToAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceRequestToAgent.Marshal(b, m, deterministic)
}
func (m *CheckDiskSpaceRequestToAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceRequestToAgent.Merge(m, src)
}
func (m *CheckDiskSpaceRequestToAgent) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceRequestToAgent.Size(m)
}
func (m *CheckDiskSpaceRequestToAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceRequestToAgent.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceRequestToAgent proto.InternalMessageInfo

type CheckDiskSpaceReplyFromAgent struct {
	ListOfFileSysUsage   []*FileSysUsage `protobuf:"bytes,1,rep,name=ListOfFileSysUsage,proto3" json:"ListOfFileSysUsage,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *CheckDiskSpaceReplyFromAgent) Reset()         { *m = CheckDiskSpaceReplyFromAgent{} }
func (m *CheckDiskSpaceReplyFromAgent) String() string { return proto.CompactTextString(m) }
func (*CheckDiskSpaceReplyFromAgent) ProtoMessage()    {}
func (*CheckDiskSpaceReplyFromAgent) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{5}
}

func (m *CheckDiskSpaceReplyFromAgent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckDiskSpaceReplyFromAgent.Unmarshal(m, b)
}
func (m *CheckDiskSpaceReplyFromAgent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckDiskSpaceReplyFromAgent.Marshal(b, m, deterministic)
}
func (m *CheckDiskSpaceReplyFromAgent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckDiskSpaceReplyFromAgent.Merge(m, src)
}
func (m *CheckDiskSpaceReplyFromAgent) XXX_Size() int {
	return xxx_messageInfo_CheckDiskSpaceReplyFromAgent.Size(m)
}
func (m *CheckDiskSpaceReplyFromAgent) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckDiskSpaceReplyFromAgent.DiscardUnknown(m)
}

var xxx_messageInfo_CheckDiskSpaceReplyFromAgent proto.InternalMessageInfo

func (m *CheckDiskSpaceReplyFromAgent) GetListOfFileSysUsage() []*FileSysUsage {
	if m != nil {
		return m.ListOfFileSysUsage
	}
	return nil
}

type CreateSegmentDataDirRequest struct {
	Datadirs             []string `protobuf:"bytes,1,rep,name=datadirs,proto3" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentDataDirRequest) Reset()         { *m = CreateSegmentDataDirRequest{} }
func (m *CreateSegmentDataDirRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentDataDirRequest) ProtoMessage()    {}
func (*CreateSegmentDataDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{6}
}

func (m *CreateSegmentDataDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Unmarshal(m, b)
}
func (m *CreateSegmentDataDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Marshal(b, m, deterministic)
}
func (m *CreateSegmentDataDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentDataDirRequest.Merge(m, src)
}
func (m *CreateSegmentDataDirRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentDataDirRequest.Size(m)
}
func (m *CreateSegmentDataDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentDataDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentDataDirRequest proto.InternalMessageInfo

func (m *CreateSegmentDataDirRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type CreateSegmentDataDirReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSegmentDataDirReply) Reset()         { *m = CreateSegmentDataDirReply{} }
func (m *CreateSegmentDataDirReply) String() string { return proto.CompactTextString(m) }
func (*CreateSegmentDataDirReply) ProtoMessage()    {}
func (*CreateSegmentDataDirReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{7}
}

func (m *CreateSegmentDataDirReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSegmentDataDirReply.Unmarshal(m, b)
}
func (m *CreateSegmentDataDirReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSegmentDataDirReply.Marshal(b, m, deterministic)
}
func (m *CreateSegmentDataDirReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSegmentDataDirReply.Merge(m, src)
}
func (m *CreateSegmentDataDirReply) XXX_Size() int {
	return xxx_messageInfo_CreateSegmentDataDirReply.Size(m)
}
func (m *CreateSegmentDataDirReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSegmentDataDirReply.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSegmentDataDirReply proto.InternalMessageInfo

type CopyMasterDirRequest struct {
	MasterDir            string   `protobuf:"bytes,1,opt,name=masterDir,proto3" json:"masterDir,omitempty"`
	Datadirs             []string `protobuf:"bytes,2,rep,name=datadirs,proto3" json:"datadirs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyMasterDirRequest) Reset()         { *m = CopyMasterDirRequest{} }
func (m *CopyMasterDirRequest) String() string { return proto.CompactTextString(m) }
func (*CopyMasterDirRequest) ProtoMessage()    {}
func (*CopyMasterDirRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{8}
}

func (m *CopyMasterDirRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyMasterDirRequest.Unmarshal(m, b)
}
func (m *CopyMasterDirRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyMasterDirRequest.Marshal(b, m, deterministic)
}
func (m *CopyMasterDirRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyMasterDirRequest.Merge(m, src)
}
func (m *CopyMasterDirRequest) XXX_Size() int {
	return xxx_messageInfo_CopyMasterDirRequest.Size(m)
}
func (m *CopyMasterDirRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyMasterDirRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CopyMasterDirRequest proto.InternalMessageInfo

func (m *CopyMasterDirRequest) GetMasterDir() string {
	if m != nil {
		return m.MasterDir
	}
	return ""
}

func (m *CopyMasterDirRequest) GetDatadirs() []string {
	if m != nil {
		return m.Datadirs
	}
	return nil
}

type CopyMasterDirReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CopyMasterDirReply) Reset()         { *m = CopyMasterDirReply{} }
func (m *CopyMasterDirReply) String() string { return proto.CompactTextString(m) }
func (*CopyMasterDirReply) ProtoMessage()    {}
func (*CopyMasterDirReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{9}
}

func (m *CopyMasterDirReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CopyMasterDirReply.Unmarshal(m, b)
}
func (m *CopyMasterDirReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CopyMasterDirReply.Marshal(b, m, deterministic)
}
func (m *CopyMasterDirReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CopyMasterDirReply.Merge(m, src)
}
func (m *CopyMasterDirReply) XXX_Size() int {
	return xxx_messageInfo_CopyMasterDirReply.Size(m)
}
func (m *CopyMasterDirReply) XXX_DiscardUnknown() {
	xxx_messageInfo_CopyMasterDirReply.DiscardUnknown(m)
}

var xxx_messageInfo_CopyMasterDirReply proto.InternalMessageInfo

type StopAgentRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentRequest) Reset()         { *m = StopAgentRequest{} }
func (m *StopAgentRequest) String() string { return proto.CompactTextString(m) }
func (*StopAgentRequest) ProtoMessage()    {}
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{10}
}

func (m *StopAgentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentRequest.Unmarshal(m, b)
}
func (m *StopAgentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentRequest.Marshal(b, m, deterministic)
}
func (m *StopAgentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentRequest.Merge(m, src)
}
func (m *StopAgentRequest) XXX_Size() int {
	return xxx_messageInfo_StopAgentRequest.Size(m)
}
func (m *StopAgentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentRequest proto.InternalMessageInfo

type StopAgentReply struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopAgentReply) Reset()         { *m = StopAgentReply{} }
func (m *StopAgentReply) String() string { return proto.CompactTextString(m) }
func (*StopAgentReply) ProtoMessage()    {}
func (*StopAgentReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_9e73bb06acc917d8, []int{11}
}

func (m *StopAgentReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopAgentReply.Unmarshal(m, b)
}
func (m *StopAgentReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopAgentReply.Marshal(b, m, deterministic)
}
func (m *StopAgentReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopAgentReply.Merge(m, src)
}
func (m *StopAgentReply) XXX_Size() int {
	return xxx_messageInfo_StopAgentReply.Size(m)
}
func (m *StopAgentReply) XXX_DiscardUnknown() {
	xxx_messageInfo_StopAgentReply.DiscardUnknown(m)
}

var xxx_messageInfo_StopAgentReply proto.InternalMessageInfo

func init() {
	proto.RegisterType((*UpgradePrimariesRequest)(nil), "idl.UpgradePrimariesRequest")
	proto.RegisterType((*DataDirPair)(nil), "idl.DataDirPair")
	proto.RegisterType((*UpgradePrimariesReply)(nil), "idl.UpgradePrimariesReply")
	proto.RegisterType((*FileSysUsage)(nil), "idl.FileSysUsage")
	proto.RegisterType((*CheckDiskSpaceRequestToAgent)(nil), "idl.CheckDiskSpaceRequestToAgent")
	proto.RegisterType((*CheckDiskSpaceReplyFromAgent)(nil), "idl.CheckDiskSpaceReplyFromAgent")
	proto.RegisterType((*CreateSegmentDataDirRequest)(nil), "idl.CreateSegmentDataDirRequest")
	proto.RegisterType((*CreateSegmentDataDirReply)(nil), "idl.CreateSegmentDataDirReply")
	proto.RegisterType((*CopyMasterDirRequest)(nil), "idl.CopyMasterDirRequest")
	proto.RegisterType((*CopyMasterDirReply)(nil), "idl.CopyMasterDirReply")
	proto.RegisterType((*StopAgentRequest)(nil), "idl.StopAgentRequest")
	proto.RegisterType((*StopAgentReply)(nil), "idl.StopAgentReply")
}

func init() { proto.RegisterFile("hub_to_agent.proto", fileDescriptor_9e73bb06acc917d8) }

var fileDescriptor_9e73bb06acc917d8 = []byte{
	// 560 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x54, 0xc1, 0x72, 0xda, 0x30,
	0x10, 0x8d, 0x43, 0x68, 0xc3, 0x26, 0xd3, 0x49, 0x55, 0x52, 0x1c, 0x87, 0x61, 0xa8, 0x7b, 0x28,
	0x27, 0x0e, 0x69, 0x2f, 0x39, 0xa6, 0xd0, 0x9c, 0x5a, 0xcc, 0xd8, 0x49, 0xaf, 0x54, 0xe0, 0x2d,
	0xd1, 0xc4, 0x58, 0xae, 0x24, 0x86, 0xfa, 0x5b, 0xfa, 0x45, 0x9d, 0xe9, 0x47, 0x75, 0x24, 0xdb,
	0x60, 0x88, 0xc9, 0x8d, 0x7d, 0x6f, 0xb5, 0xfb, 0xf4, 0x9e, 0x30, 0x90, 0x87, 0xe5, 0x74, 0xa2,
	0xf8, 0x84, 0xce, 0x31, 0x56, 0xfd, 0x44, 0x70, 0xc5, 0x49, 0x8d, 0x85, 0x91, 0xfb, 0xd7, 0x82,
	0xd6, 0x7d, 0x32, 0x17, 0x34, 0xc4, 0xb1, 0x60, 0x0b, 0x2a, 0x18, 0x4a, 0x1f, 0x7f, 0x2d, 0x51,
	0x2a, 0xd2, 0x86, 0x86, 0x17, 0x85, 0x9f, 0x59, 0x3c, 0x64, 0xc2, 0xb6, 0xba, 0x56, 0xaf, 0xe1,
	0x6f, 0x00, 0xcd, 0x8e, 0x70, 0x95, 0xb3, 0x87, 0x19, 0xbb, 0x06, 0x48, 0x07, 0x60, 0x84, 0xab,
	0xef, 0x28, 0x24, 0xe3, 0xb1, 0x5d, 0x33, 0x74, 0x09, 0x21, 0x9f, 0xe0, 0x74, 0x48, 0x15, 0x1d,
	0x32, 0x31, 0xa6, 0x4c, 0x48, 0xfb, 0xa8, 0x5b, 0xeb, 0x9d, 0x5c, 0x9d, 0xf5, 0x59, 0x18, 0xf5,
	0x4b, 0x84, 0xbf, 0xd5, 0xa5, 0x77, 0x0e, 0x1e, 0x70, 0xf6, 0xe8, 0xc5, 0x51, 0x6a, 0xd7, 0xbb,
	0x56, 0xef, 0xd8, 0xdf, 0x00, 0xee, 0x1f, 0x0b, 0x4e, 0x4a, 0xed, 0x5a, 0x83, 0x17, 0x85, 0x39,
	0x92, 0x5f, 0xa0, 0x84, 0xe4, 0x1a, 0x0b, 0xfe, 0x70, 0xad, 0xb1, 0xe0, 0x6d, 0x78, 0xe9, 0x45,
	0xe1, 0x98, 0x0b, 0x65, 0x2e, 0x50, 0xf7, 0x8b, 0x52, 0x33, 0x23, 0x5c, 0x19, 0xe6, 0x28, 0x63,
	0xf2, 0x52, 0x33, 0x03, 0x1e, 0x2b, 0x8c, 0x95, 0xd1, 0x57, 0xf7, 0x8b, 0xd2, 0x6d, 0xc1, 0xf9,
	0x53, 0xa3, 0x93, 0x28, 0x75, 0x87, 0x70, 0x7a, 0xcb, 0x22, 0x0c, 0x52, 0x79, 0x2f, 0xe9, 0x1c,
	0xb5, 0x2c, 0x5d, 0xcb, 0x54, 0x2a, 0x5c, 0x14, 0xb2, 0x37, 0x08, 0x69, 0x42, 0xdd, 0x34, 0x1a,
	0xc5, 0x96, 0x9f, 0x15, 0x6e, 0x07, 0xda, 0xc6, 0x89, 0x21, 0x93, 0x8f, 0x41, 0x42, 0x67, 0x98,
	0xa7, 0x78, 0xc7, 0x6f, 0x74, 0xe6, 0x2e, 0x7d, 0xca, 0x27, 0x51, 0x7a, 0x2b, 0xf8, 0xc2, 0xf0,
	0xe4, 0x06, 0xc8, 0x57, 0x26, 0x95, 0xf7, 0xb3, 0xac, 0xc5, 0xb6, 0x4c, 0x2c, 0xaf, 0x4d, 0x2c,
	0x65, 0xc2, 0xaf, 0x68, 0x76, 0xaf, 0xe1, 0x72, 0x20, 0x90, 0x2a, 0x0c, 0x70, 0xbe, 0xc0, 0x58,
	0xe5, 0x3e, 0x16, 0xcf, 0xc9, 0x81, 0xe3, 0x90, 0x2a, 0x1a, 0xea, 0xb8, 0xf5, 0xdc, 0x86, 0xbf,
	0xae, 0xdd, 0x4b, 0xb8, 0xa8, 0x3e, 0xaa, 0x0d, 0x1a, 0x43, 0x73, 0xc0, 0x93, 0xf4, 0x1b, 0x95,
	0x0a, 0x45, 0x69, 0x60, 0x1b, 0x1a, 0x8b, 0x02, 0x2b, 0xde, 0xe7, 0x1a, 0xd8, 0x5a, 0x77, 0xb8,
	0xb3, 0xae, 0x09, 0x64, 0x67, 0xa2, 0xde, 0x43, 0xe0, 0x2c, 0x50, 0x3c, 0x31, 0x7e, 0xe4, 0x3b,
	0xdc, 0x33, 0x78, 0x55, 0xc2, 0x92, 0x28, 0xbd, 0xfa, 0x57, 0x83, 0x7a, 0x66, 0xd9, 0x0f, 0x78,
	0xbb, 0x6d, 0xa9, 0x17, 0x1b, 0x42, 0x92, 0x77, 0xc6, 0xb0, 0xe7, 0xf2, 0x70, 0xaa, 0x5b, 0xca,
	0x91, 0xb8, 0x07, 0x84, 0xc2, 0x7b, 0xf3, 0xf3, 0xcb, 0x6f, 0x9c, 0x2d, 0x15, 0xee, 0xbe, 0x9f,
	0x60, 0x39, 0x0d, 0x14, 0x26, 0xa4, 0x6d, 0x66, 0xed, 0xf9, 0x1b, 0x3b, 0xce, 0x1e, 0x56, 0x5f,
	0xf9, 0x80, 0x4c, 0xa1, 0x5d, 0xe5, 0x3c, 0xce, 0x14, 0xd7, 0x6d, 0xa4, 0x9b, 0xe9, 0xdc, 0x9f,
	0xab, 0xd3, 0x79, 0xa6, 0x23, 0xdb, 0x31, 0x81, 0x0f, 0x5b, 0x76, 0x9b, 0xe1, 0xe9, 0x1d, 0x2f,
	0xba, 0x4b, 0xeb, 0x2e, 0xb2, 0x61, 0x15, 0x71, 0x3b, 0xad, 0x2a, 0x2a, 0x5b, 0x70, 0x0d, 0x8d,
	0x75, 0x4a, 0xe4, 0xdc, 0xf4, 0xed, 0x26, 0xe9, 0xbc, 0xd9, 0x85, 0xcd, 0xd1, 0xe9, 0x0b, 0xf3,
	0x31, 0xfc, 0xf8, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x29, 0x34, 0xb7, 0xf2, 0x22, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AgentClient is the client API for Agent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AgentClient interface {
	CheckDiskSpaceOnAgents(ctx context.Context, in *CheckDiskSpaceRequestToAgent, opts ...grpc.CallOption) (*CheckDiskSpaceReplyFromAgent, error)
	AgentExecuteUpgradePrimariesSubStep(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error)
	CreateSegmentDataDirectories(ctx context.Context, in *CreateSegmentDataDirRequest, opts ...grpc.CallOption) (*CreateSegmentDataDirReply, error)
	CopyMasterDirectoryToSegmentDirectories(ctx context.Context, in *CopyMasterDirRequest, opts ...grpc.CallOption) (*CopyMasterDirReply, error)
	StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error)
}

type agentClient struct {
	cc *grpc.ClientConn
}

func NewAgentClient(cc *grpc.ClientConn) AgentClient {
	return &agentClient{cc}
}

func (c *agentClient) CheckDiskSpaceOnAgents(ctx context.Context, in *CheckDiskSpaceRequestToAgent, opts ...grpc.CallOption) (*CheckDiskSpaceReplyFromAgent, error) {
	out := new(CheckDiskSpaceReplyFromAgent)
	err := c.cc.Invoke(ctx, "/idl.Agent/CheckDiskSpaceOnAgents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) AgentExecuteUpgradePrimariesSubStep(ctx context.Context, in *UpgradePrimariesRequest, opts ...grpc.CallOption) (*UpgradePrimariesReply, error) {
	out := new(UpgradePrimariesReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/AgentExecuteUpgradePrimariesSubStep", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CreateSegmentDataDirectories(ctx context.Context, in *CreateSegmentDataDirRequest, opts ...grpc.CallOption) (*CreateSegmentDataDirReply, error) {
	out := new(CreateSegmentDataDirReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/CreateSegmentDataDirectories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) CopyMasterDirectoryToSegmentDirectories(ctx context.Context, in *CopyMasterDirRequest, opts ...grpc.CallOption) (*CopyMasterDirReply, error) {
	out := new(CopyMasterDirReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/CopyMasterDirectoryToSegmentDirectories", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentClient) StopAgent(ctx context.Context, in *StopAgentRequest, opts ...grpc.CallOption) (*StopAgentReply, error) {
	out := new(StopAgentReply)
	err := c.cc.Invoke(ctx, "/idl.Agent/StopAgent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentServer is the server API for Agent service.
type AgentServer interface {
	CheckDiskSpaceOnAgents(context.Context, *CheckDiskSpaceRequestToAgent) (*CheckDiskSpaceReplyFromAgent, error)
	AgentExecuteUpgradePrimariesSubStep(context.Context, *UpgradePrimariesRequest) (*UpgradePrimariesReply, error)
	CreateSegmentDataDirectories(context.Context, *CreateSegmentDataDirRequest) (*CreateSegmentDataDirReply, error)
	CopyMasterDirectoryToSegmentDirectories(context.Context, *CopyMasterDirRequest) (*CopyMasterDirReply, error)
	StopAgent(context.Context, *StopAgentRequest) (*StopAgentReply, error)
}

// UnimplementedAgentServer can be embedded to have forward compatible implementations.
type UnimplementedAgentServer struct {
}

func (*UnimplementedAgentServer) CheckDiskSpaceOnAgents(ctx context.Context, req *CheckDiskSpaceRequestToAgent) (*CheckDiskSpaceReplyFromAgent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckDiskSpaceOnAgents not implemented")
}
func (*UnimplementedAgentServer) AgentExecuteUpgradePrimariesSubStep(ctx context.Context, req *UpgradePrimariesRequest) (*UpgradePrimariesReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AgentExecuteUpgradePrimariesSubStep not implemented")
}
func (*UnimplementedAgentServer) CreateSegmentDataDirectories(ctx context.Context, req *CreateSegmentDataDirRequest) (*CreateSegmentDataDirReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSegmentDataDirectories not implemented")
}
func (*UnimplementedAgentServer) CopyMasterDirectoryToSegmentDirectories(ctx context.Context, req *CopyMasterDirRequest) (*CopyMasterDirReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyMasterDirectoryToSegmentDirectories not implemented")
}
func (*UnimplementedAgentServer) StopAgent(ctx context.Context, req *StopAgentRequest) (*StopAgentReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopAgent not implemented")
}

func RegisterAgentServer(s *grpc.Server, srv AgentServer) {
	s.RegisterService(&_Agent_serviceDesc, srv)
}

func _Agent_CheckDiskSpaceOnAgents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckDiskSpaceRequestToAgent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CheckDiskSpaceOnAgents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CheckDiskSpaceOnAgents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CheckDiskSpaceOnAgents(ctx, req.(*CheckDiskSpaceRequestToAgent))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_AgentExecuteUpgradePrimariesSubStep_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpgradePrimariesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).AgentExecuteUpgradePrimariesSubStep(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/AgentExecuteUpgradePrimariesSubStep",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).AgentExecuteUpgradePrimariesSubStep(ctx, req.(*UpgradePrimariesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CreateSegmentDataDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSegmentDataDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CreateSegmentDataDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CreateSegmentDataDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CreateSegmentDataDirectories(ctx, req.(*CreateSegmentDataDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_CopyMasterDirectoryToSegmentDirectories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyMasterDirRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).CopyMasterDirectoryToSegmentDirectories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/CopyMasterDirectoryToSegmentDirectories",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).CopyMasterDirectoryToSegmentDirectories(ctx, req.(*CopyMasterDirRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Agent_StopAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopAgentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentServer).StopAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/idl.Agent/StopAgent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentServer).StopAgent(ctx, req.(*StopAgentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Agent_serviceDesc = grpc.ServiceDesc{
	ServiceName: "idl.Agent",
	HandlerType: (*AgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckDiskSpaceOnAgents",
			Handler:    _Agent_CheckDiskSpaceOnAgents_Handler,
		},
		{
			MethodName: "AgentExecuteUpgradePrimariesSubStep",
			Handler:    _Agent_AgentExecuteUpgradePrimariesSubStep_Handler,
		},
		{
			MethodName: "CreateSegmentDataDirectories",
			Handler:    _Agent_CreateSegmentDataDirectories_Handler,
		},
		{
			MethodName: "CopyMasterDirectoryToSegmentDirectories",
			Handler:    _Agent_CopyMasterDirectoryToSegmentDirectories_Handler,
		},
		{
			MethodName: "StopAgent",
			Handler:    _Agent_StopAgent_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hub_to_agent.proto",
}
