// Copyright (c) 2017-2020 VMware, Inc. or its affiliates
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.4
// source: hub_to_agent.proto

package idl

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TablespaceInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Location    string `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	UserDefined bool   `protobuf:"varint,5,opt,name=UserDefined,proto3" json:"UserDefined,omitempty"`
}

func (x *TablespaceInfo) Reset() {
	*x = TablespaceInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TablespaceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TablespaceInfo) ProtoMessage() {}

func (x *TablespaceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TablespaceInfo.ProtoReflect.Descriptor instead.
func (*TablespaceInfo) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{0}
}

func (x *TablespaceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TablespaceInfo) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *TablespaceInfo) GetUserDefined() bool {
	if x != nil {
		return x.UserDefined
	}
	return false
}

type UpgradePrimariesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceBinDir               string         `protobuf:"bytes,1,opt,name=SourceBinDir,proto3" json:"SourceBinDir,omitempty"`
	TargetBinDir               string         `protobuf:"bytes,2,opt,name=TargetBinDir,proto3" json:"TargetBinDir,omitempty"`
	TargetVersion              string         `protobuf:"bytes,3,opt,name=TargetVersion,proto3" json:"TargetVersion,omitempty"`
	DataDirPairs               []*DataDirPair `protobuf:"bytes,4,rep,name=DataDirPairs,proto3" json:"DataDirPairs,omitempty"`
	CheckOnly                  bool           `protobuf:"varint,5,opt,name=CheckOnly,proto3" json:"CheckOnly,omitempty"`
	UseLinkMode                bool           `protobuf:"varint,6,opt,name=UseLinkMode,proto3" json:"UseLinkMode,omitempty"`
	MasterBackupDir            string         `protobuf:"bytes,7,opt,name=MasterBackupDir,proto3" json:"MasterBackupDir,omitempty"`
	TablespacesMappingFilePath string         `protobuf:"bytes,8,opt,name=TablespacesMappingFilePath,proto3" json:"TablespacesMappingFilePath,omitempty"`
}

func (x *UpgradePrimariesRequest) Reset() {
	*x = UpgradePrimariesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradePrimariesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePrimariesRequest) ProtoMessage() {}

func (x *UpgradePrimariesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePrimariesRequest.ProtoReflect.Descriptor instead.
func (*UpgradePrimariesRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{1}
}

func (x *UpgradePrimariesRequest) GetSourceBinDir() string {
	if x != nil {
		return x.SourceBinDir
	}
	return ""
}

func (x *UpgradePrimariesRequest) GetTargetBinDir() string {
	if x != nil {
		return x.TargetBinDir
	}
	return ""
}

func (x *UpgradePrimariesRequest) GetTargetVersion() string {
	if x != nil {
		return x.TargetVersion
	}
	return ""
}

func (x *UpgradePrimariesRequest) GetDataDirPairs() []*DataDirPair {
	if x != nil {
		return x.DataDirPairs
	}
	return nil
}

func (x *UpgradePrimariesRequest) GetCheckOnly() bool {
	if x != nil {
		return x.CheckOnly
	}
	return false
}

func (x *UpgradePrimariesRequest) GetUseLinkMode() bool {
	if x != nil {
		return x.UseLinkMode
	}
	return false
}

func (x *UpgradePrimariesRequest) GetMasterBackupDir() string {
	if x != nil {
		return x.MasterBackupDir
	}
	return ""
}

func (x *UpgradePrimariesRequest) GetTablespacesMappingFilePath() string {
	if x != nil {
		return x.TablespacesMappingFilePath
	}
	return ""
}

type DataDirPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SourceDataDir string                    `protobuf:"bytes,1,opt,name=SourceDataDir,proto3" json:"SourceDataDir,omitempty"`
	TargetDataDir string                    `protobuf:"bytes,2,opt,name=TargetDataDir,proto3" json:"TargetDataDir,omitempty"`
	SourcePort    int32                     `protobuf:"varint,3,opt,name=SourcePort,proto3" json:"SourcePort,omitempty"`
	TargetPort    int32                     `protobuf:"varint,4,opt,name=TargetPort,proto3" json:"TargetPort,omitempty"`
	Content       int32                     `protobuf:"varint,5,opt,name=Content,proto3" json:"Content,omitempty"`
	DBID          int32                     `protobuf:"varint,6,opt,name=DBID,proto3" json:"DBID,omitempty"`
	Tablespaces   map[int32]*TablespaceInfo `protobuf:"bytes,7,rep,name=Tablespaces,proto3" json:"Tablespaces,omitempty" protobuf_key:"varint,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DataDirPair) Reset() {
	*x = DataDirPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataDirPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataDirPair) ProtoMessage() {}

func (x *DataDirPair) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataDirPair.ProtoReflect.Descriptor instead.
func (*DataDirPair) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{2}
}

func (x *DataDirPair) GetSourceDataDir() string {
	if x != nil {
		return x.SourceDataDir
	}
	return ""
}

func (x *DataDirPair) GetTargetDataDir() string {
	if x != nil {
		return x.TargetDataDir
	}
	return ""
}

func (x *DataDirPair) GetSourcePort() int32 {
	if x != nil {
		return x.SourcePort
	}
	return 0
}

func (x *DataDirPair) GetTargetPort() int32 {
	if x != nil {
		return x.TargetPort
	}
	return 0
}

func (x *DataDirPair) GetContent() int32 {
	if x != nil {
		return x.Content
	}
	return 0
}

func (x *DataDirPair) GetDBID() int32 {
	if x != nil {
		return x.DBID
	}
	return 0
}

func (x *DataDirPair) GetTablespaces() map[int32]*TablespaceInfo {
	if x != nil {
		return x.Tablespaces
	}
	return nil
}

type UpgradePrimariesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpgradePrimariesReply) Reset() {
	*x = UpgradePrimariesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpgradePrimariesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpgradePrimariesReply) ProtoMessage() {}

func (x *UpgradePrimariesReply) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpgradePrimariesReply.ProtoReflect.Descriptor instead.
func (*UpgradePrimariesReply) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{3}
}

type DeleteDataDirectoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Datadirs []string `protobuf:"bytes,1,rep,name=datadirs,proto3" json:"datadirs,omitempty"`
}

func (x *DeleteDataDirectoriesRequest) Reset() {
	*x = DeleteDataDirectoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataDirectoriesRequest) ProtoMessage() {}

func (x *DeleteDataDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataDirectoriesRequest.ProtoReflect.Descriptor instead.
func (*DeleteDataDirectoriesRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteDataDirectoriesRequest) GetDatadirs() []string {
	if x != nil {
		return x.Datadirs
	}
	return nil
}

type DeleteDataDirectoriesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteDataDirectoriesReply) Reset() {
	*x = DeleteDataDirectoriesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteDataDirectoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDataDirectoriesReply) ProtoMessage() {}

func (x *DeleteDataDirectoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDataDirectoriesReply.ProtoReflect.Descriptor instead.
func (*DeleteDataDirectoriesReply) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{5}
}

type DeleteStateDirectoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteStateDirectoryRequest) Reset() {
	*x = DeleteStateDirectoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStateDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateDirectoryRequest) ProtoMessage() {}

func (x *DeleteStateDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateDirectoryRequest.ProtoReflect.Descriptor instead.
func (*DeleteStateDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{6}
}

type DeleteStateDirectoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteStateDirectoryReply) Reset() {
	*x = DeleteStateDirectoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteStateDirectoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStateDirectoryReply) ProtoMessage() {}

func (x *DeleteStateDirectoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStateDirectoryReply.ProtoReflect.Descriptor instead.
func (*DeleteStateDirectoryReply) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{7}
}

type DeleteTablespaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dirs []string `protobuf:"bytes,1,rep,name=dirs,proto3" json:"dirs,omitempty"`
}

func (x *DeleteTablespaceRequest) Reset() {
	*x = DeleteTablespaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTablespaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTablespaceRequest) ProtoMessage() {}

func (x *DeleteTablespaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTablespaceRequest.ProtoReflect.Descriptor instead.
func (*DeleteTablespaceRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteTablespaceRequest) GetDirs() []string {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type DeleteTablespaceReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteTablespaceReply) Reset() {
	*x = DeleteTablespaceReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTablespaceReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTablespaceReply) ProtoMessage() {}

func (x *DeleteTablespaceReply) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTablespaceReply.ProtoReflect.Descriptor instead.
func (*DeleteTablespaceReply) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{9}
}

type ArchiveLogDirectoryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewDir string `protobuf:"bytes,1,opt,name=NewDir,proto3" json:"NewDir,omitempty"`
}

func (x *ArchiveLogDirectoryRequest) Reset() {
	*x = ArchiveLogDirectoryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveLogDirectoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveLogDirectoryRequest) ProtoMessage() {}

func (x *ArchiveLogDirectoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveLogDirectoryRequest.ProtoReflect.Descriptor instead.
func (*ArchiveLogDirectoryRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{10}
}

func (x *ArchiveLogDirectoryRequest) GetNewDir() string {
	if x != nil {
		return x.NewDir
	}
	return ""
}

type ArchiveLogDirectoryReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ArchiveLogDirectoryReply) Reset() {
	*x = ArchiveLogDirectoryReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArchiveLogDirectoryReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveLogDirectoryReply) ProtoMessage() {}

func (x *ArchiveLogDirectoryReply) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveLogDirectoryReply.ProtoReflect.Descriptor instead.
func (*ArchiveLogDirectoryReply) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{11}
}

type RenameDirectories struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source       string `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	Target       string `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
	RenameTarget bool   `protobuf:"varint,3,opt,name=RenameTarget,proto3" json:"RenameTarget,omitempty"`
}

func (x *RenameDirectories) Reset() {
	*x = RenameDirectories{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameDirectories) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameDirectories) ProtoMessage() {}

func (x *RenameDirectories) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameDirectories.ProtoReflect.Descriptor instead.
func (*RenameDirectories) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{12}
}

func (x *RenameDirectories) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RenameDirectories) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *RenameDirectories) GetRenameTarget() bool {
	if x != nil {
		return x.RenameTarget
	}
	return false
}

type RenameDirectoriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Dirs []*RenameDirectories `protobuf:"bytes,1,rep,name=Dirs,proto3" json:"Dirs,omitempty"`
}

func (x *RenameDirectoriesRequest) Reset() {
	*x = RenameDirectoriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameDirectoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameDirectoriesRequest) ProtoMessage() {}

func (x *RenameDirectoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameDirectoriesRequest.ProtoReflect.Descriptor instead.
func (*RenameDirectoriesRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{13}
}

func (x *RenameDirectoriesRequest) GetDirs() []*RenameDirectories {
	if x != nil {
		return x.Dirs
	}
	return nil
}

type RenameDirectoriesReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RenameDirectoriesReply) Reset() {
	*x = RenameDirectoriesReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RenameDirectoriesReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenameDirectoriesReply) ProtoMessage() {}

func (x *RenameDirectoriesReply) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenameDirectoriesReply.ProtoReflect.Descriptor instead.
func (*RenameDirectoriesReply) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{14}
}

type StopAgentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopAgentRequest) Reset() {
	*x = StopAgentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAgentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentRequest) ProtoMessage() {}

func (x *StopAgentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentRequest.ProtoReflect.Descriptor instead.
func (*StopAgentRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{15}
}

type StopAgentReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StopAgentReply) Reset() {
	*x = StopAgentReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StopAgentReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopAgentReply) ProtoMessage() {}

func (x *StopAgentReply) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopAgentReply.ProtoReflect.Descriptor instead.
func (*StopAgentReply) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{16}
}

type CheckSegmentDiskSpaceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Request  *CheckDiskSpaceRequest `protobuf:"bytes,1,opt,name=request,proto3" json:"request,omitempty"`
	Datadirs []string               `protobuf:"bytes,2,rep,name=datadirs,proto3" json:"datadirs,omitempty"`
}

func (x *CheckSegmentDiskSpaceRequest) Reset() {
	*x = CheckSegmentDiskSpaceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckSegmentDiskSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckSegmentDiskSpaceRequest) ProtoMessage() {}

func (x *CheckSegmentDiskSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckSegmentDiskSpaceRequest.ProtoReflect.Descriptor instead.
func (*CheckSegmentDiskSpaceRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{17}
}

func (x *CheckSegmentDiskSpaceRequest) GetRequest() *CheckDiskSpaceRequest {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *CheckSegmentDiskSpaceRequest) GetDatadirs() []string {
	if x != nil {
		return x.Datadirs
	}
	return nil
}

type RsyncPair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source          string `protobuf:"bytes,1,opt,name=Source,proto3" json:"Source,omitempty"`
	DestinationHost string `protobuf:"bytes,2,opt,name=DestinationHost,proto3" json:"DestinationHost,omitempty"`
	Destination     string `protobuf:"bytes,3,opt,name=Destination,proto3" json:"Destination,omitempty"`
}

func (x *RsyncPair) Reset() {
	*x = RsyncPair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncPair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncPair) ProtoMessage() {}

func (x *RsyncPair) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncPair.ProtoReflect.Descriptor instead.
func (*RsyncPair) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{18}
}

func (x *RsyncPair) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *RsyncPair) GetDestinationHost() string {
	if x != nil {
		return x.DestinationHost
	}
	return ""
}

func (x *RsyncPair) GetDestination() string {
	if x != nil {
		return x.Destination
	}
	return ""
}

type RsyncRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Options  []string     `protobuf:"bytes,1,rep,name=Options,proto3" json:"Options,omitempty"`
	Excludes []string     `protobuf:"bytes,2,rep,name=Excludes,proto3" json:"Excludes,omitempty"`
	Pairs    []*RsyncPair `protobuf:"bytes,3,rep,name=Pairs,proto3" json:"Pairs,omitempty"`
}

func (x *RsyncRequest) Reset() {
	*x = RsyncRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncRequest) ProtoMessage() {}

func (x *RsyncRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncRequest.ProtoReflect.Descriptor instead.
func (*RsyncRequest) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{19}
}

func (x *RsyncRequest) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *RsyncRequest) GetExcludes() []string {
	if x != nil {
		return x.Excludes
	}
	return nil
}

func (x *RsyncRequest) GetPairs() []*RsyncPair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type RsyncReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RsyncReply) Reset() {
	*x = RsyncReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_hub_to_agent_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RsyncReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RsyncReply) ProtoMessage() {}

func (x *RsyncReply) ProtoReflect() protoreflect.Message {
	mi := &file_hub_to_agent_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RsyncReply.ProtoReflect.Descriptor instead.
func (*RsyncReply) Descriptor() ([]byte, []int) {
	return file_hub_to_agent_proto_rawDescGZIP(), []int{20}
}

var File_hub_to_agent_proto protoreflect.FileDescriptor

var file_hub_to_agent_proto_rawDesc = []byte{
	0x0a, 0x12, 0x68, 0x75, 0x62, 0x5f, 0x74, 0x6f, 0x5f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x69, 0x64, 0x6c, 0x1a, 0x10, 0x63, 0x6c, 0x69, 0x5f, 0x74,
	0x6f, 0x5f, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x62, 0x0a, 0x0e, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a,
	0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20, 0x0a,
	0x0b, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x44, 0x65, 0x66, 0x69, 0x6e, 0x65, 0x64, 0x22,
	0xe7, 0x02, 0x0a, 0x17, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x69, 0x6d, 0x61,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x69, 0x6e, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x69, 0x6e, 0x44, 0x69, 0x72, 0x12,
	0x22, 0x0a, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x69, 0x6e, 0x44, 0x69, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x42, 0x69, 0x6e,
	0x44, 0x69, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x61, 0x72, 0x67,
	0x65, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x34, 0x0a, 0x0c, 0x44, 0x61, 0x74,
	0x61, 0x44, 0x69, 0x72, 0x50, 0x61, 0x69, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x50, 0x61, 0x69,
	0x72, 0x52, 0x0c, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x50, 0x61, 0x69, 0x72, 0x73, 0x12,
	0x1c, 0x0a, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x6e, 0x6c, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x4f, 0x6e, 0x6c, 0x79, 0x12, 0x20, 0x0a,
	0x0b, 0x55, 0x73, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0b, 0x55, 0x73, 0x65, 0x4c, 0x69, 0x6e, 0x6b, 0x4d, 0x6f, 0x64, 0x65, 0x12,
	0x28, 0x0a, 0x0f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44,
	0x69, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x4d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x42, 0x61, 0x63, 0x6b, 0x75, 0x70, 0x44, 0x69, 0x72, 0x12, 0x3e, 0x0a, 0x1a, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e, 0x67, 0x46,
	0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x1a, 0x54,
	0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x4d, 0x61, 0x70, 0x70, 0x69, 0x6e,
	0x67, 0x46, 0x69, 0x6c, 0x65, 0x50, 0x61, 0x74, 0x68, 0x22, 0xe1, 0x02, 0x0a, 0x0b, 0x44, 0x61,
	0x74, 0x61, 0x44, 0x69, 0x72, 0x50, 0x61, 0x69, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0d, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x12,
	0x24, 0x0a, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x44, 0x61,
	0x74, 0x61, 0x44, 0x69, 0x72, 0x12, 0x1e, 0x0a, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x53, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x50,
	0x6f, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x54, 0x61, 0x72, 0x67, 0x65,
	0x74, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x44, 0x42, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x44,
	0x42, 0x49, 0x44, 0x12, 0x43, 0x0a, 0x0b, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63,
	0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x44,
	0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x50, 0x61, 0x69, 0x72, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65,
	0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x54, 0x61, 0x62,
	0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x1a, 0x53, 0x0a, 0x10, 0x54, 0x61, 0x62, 0x6c,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x29,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e,
	0x69, 0x64, 0x6c, 0x2e, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x17, 0x0a,
	0x15, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x3a, 0x0a, 0x1c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x61, 0x74, 0x61, 0x64, 0x69,
	0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x64, 0x61, 0x74, 0x61, 0x64, 0x69,
	0x72, 0x73, 0x22, 0x1c, 0x0a, 0x1a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x1d, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44,
	0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22,
	0x1b, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x69,
	0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x2d, 0x0a, 0x17,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x69, 0x72, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x69, 0x72, 0x73, 0x22, 0x17, 0x0a, 0x15, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x34, 0x0a, 0x1a, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c,
	0x6f, 0x67, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x4e, 0x65, 0x77, 0x44, 0x69, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x4e, 0x65, 0x77, 0x44, 0x69, 0x72, 0x22, 0x1a, 0x0a, 0x18, 0x41, 0x72,
	0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x67, 0x0a, 0x11, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x52,
	0x65, 0x6e, 0x61, 0x6d, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0c, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x54, 0x61, 0x72, 0x67, 0x65, 0x74, 0x22,
	0x46, 0x0a, 0x18, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2a, 0x0a, 0x04, 0x44,
	0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x69, 0x64, 0x6c, 0x2e,
	0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x04, 0x44, 0x69, 0x72, 0x73, 0x22, 0x18, 0x0a, 0x16, 0x52, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x10, 0x0a, 0x0e, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x67, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x70, 0x0a, 0x1c, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x53, 0x65, 0x67, 0x6d, 0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x64, 0x69, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x08, 0x64, 0x61, 0x74, 0x61, 0x64, 0x69, 0x72, 0x73, 0x22, 0x6f, 0x0a, 0x09, 0x52, 0x73, 0x79,
	0x6e, 0x63, 0x50, 0x61, 0x69, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x28,
	0x0a, 0x0f, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x6f, 0x73,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0f, 0x44, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x44, 0x65, 0x73, 0x74,
	0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x44,
	0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6a, 0x0a, 0x0c, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x45, 0x78, 0x63, 0x6c, 0x75, 0x64, 0x65, 0x73,
	0x12, 0x24, 0x0a, 0x05, 0x50, 0x61, 0x69, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x50, 0x61, 0x69, 0x72, 0x52,
	0x05, 0x50, 0x61, 0x69, 0x72, 0x73, 0x22, 0x0c, 0x0a, 0x0a, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x32, 0x92, 0x06, 0x0a, 0x05, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12, 0x4f,
	0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x70, 0x61, 0x63, 0x65,
	0x12, 0x21, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x53, 0x65, 0x67, 0x6d,
	0x65, 0x6e, 0x74, 0x44, 0x69, 0x73, 0x6b, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x18, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x44,
	0x69, 0x73, 0x6b, 0x53, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x4e, 0x0a, 0x10, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72,
	0x69, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64,
	0x65, 0x50, 0x72, 0x69, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x55, 0x70, 0x67, 0x72, 0x61, 0x64, 0x65, 0x50,
	0x72, 0x69, 0x6d, 0x61, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x51, 0x0a, 0x11, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x1d, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d,
	0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x65, 0x6e, 0x61, 0x6d, 0x65,
	0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x22, 0x00, 0x12, 0x39, 0x0a, 0x09, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x12,
	0x15, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x53, 0x74, 0x6f, 0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x53, 0x74, 0x6f,
	0x70, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5d, 0x0a,
	0x15, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x21, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x69,
	0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x69, 0x64, 0x6c, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x5a, 0x0a, 0x14,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72,
	0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x59, 0x0a, 0x1b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x1c, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x54, 0x61, 0x62, 0x6c, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x13, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x6f,
	0x67, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x1f, 0x2e, 0x69, 0x64, 0x6c,
	0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x69, 0x64,
	0x6c, 0x2e, 0x41, 0x72, 0x63, 0x68, 0x69, 0x76, 0x65, 0x4c, 0x6f, 0x67, 0x44, 0x69, 0x72, 0x65,
	0x63, 0x74, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x3c, 0x0a, 0x14,
	0x52, 0x73, 0x79, 0x6e, 0x63, 0x44, 0x61, 0x74, 0x61, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x69, 0x65, 0x73, 0x12, 0x11, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x2d, 0x0a, 0x05, 0x52, 0x73,
	0x79, 0x6e, 0x63, 0x12, 0x11, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x73, 0x79, 0x6e, 0x63, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x69, 0x64, 0x6c, 0x2e, 0x52, 0x73, 0x79,
	0x6e, 0x63, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x69, 0x64, 0x6c,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_hub_to_agent_proto_rawDescOnce sync.Once
	file_hub_to_agent_proto_rawDescData = file_hub_to_agent_proto_rawDesc
)

func file_hub_to_agent_proto_rawDescGZIP() []byte {
	file_hub_to_agent_proto_rawDescOnce.Do(func() {
		file_hub_to_agent_proto_rawDescData = protoimpl.X.CompressGZIP(file_hub_to_agent_proto_rawDescData)
	})
	return file_hub_to_agent_proto_rawDescData
}

var file_hub_to_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_hub_to_agent_proto_goTypes = []interface{}{
	(*TablespaceInfo)(nil),               // 0: idl.TablespaceInfo
	(*UpgradePrimariesRequest)(nil),      // 1: idl.UpgradePrimariesRequest
	(*DataDirPair)(nil),                  // 2: idl.DataDirPair
	(*UpgradePrimariesReply)(nil),        // 3: idl.UpgradePrimariesReply
	(*DeleteDataDirectoriesRequest)(nil), // 4: idl.DeleteDataDirectoriesRequest
	(*DeleteDataDirectoriesReply)(nil),   // 5: idl.DeleteDataDirectoriesReply
	(*DeleteStateDirectoryRequest)(nil),  // 6: idl.DeleteStateDirectoryRequest
	(*DeleteStateDirectoryReply)(nil),    // 7: idl.DeleteStateDirectoryReply
	(*DeleteTablespaceRequest)(nil),      // 8: idl.DeleteTablespaceRequest
	(*DeleteTablespaceReply)(nil),        // 9: idl.DeleteTablespaceReply
	(*ArchiveLogDirectoryRequest)(nil),   // 10: idl.ArchiveLogDirectoryRequest
	(*ArchiveLogDirectoryReply)(nil),     // 11: idl.ArchiveLogDirectoryReply
	(*RenameDirectories)(nil),            // 12: idl.RenameDirectories
	(*RenameDirectoriesRequest)(nil),     // 13: idl.RenameDirectoriesRequest
	(*RenameDirectoriesReply)(nil),       // 14: idl.RenameDirectoriesReply
	(*StopAgentRequest)(nil),             // 15: idl.StopAgentRequest
	(*StopAgentReply)(nil),               // 16: idl.StopAgentReply
	(*CheckSegmentDiskSpaceRequest)(nil), // 17: idl.CheckSegmentDiskSpaceRequest
	(*RsyncPair)(nil),                    // 18: idl.RsyncPair
	(*RsyncRequest)(nil),                 // 19: idl.RsyncRequest
	(*RsyncReply)(nil),                   // 20: idl.RsyncReply
	nil,                                  // 21: idl.DataDirPair.TablespacesEntry
	(*CheckDiskSpaceRequest)(nil),        // 22: idl.CheckDiskSpaceRequest
	(*CheckDiskSpaceReply)(nil),          // 23: idl.CheckDiskSpaceReply
}
var file_hub_to_agent_proto_depIdxs = []int32{
	2,  // 0: idl.UpgradePrimariesRequest.DataDirPairs:type_name -> idl.DataDirPair
	21, // 1: idl.DataDirPair.Tablespaces:type_name -> idl.DataDirPair.TablespacesEntry
	12, // 2: idl.RenameDirectoriesRequest.Dirs:type_name -> idl.RenameDirectories
	22, // 3: idl.CheckSegmentDiskSpaceRequest.request:type_name -> idl.CheckDiskSpaceRequest
	18, // 4: idl.RsyncRequest.Pairs:type_name -> idl.RsyncPair
	0,  // 5: idl.DataDirPair.TablespacesEntry.value:type_name -> idl.TablespaceInfo
	17, // 6: idl.Agent.CheckDiskSpace:input_type -> idl.CheckSegmentDiskSpaceRequest
	1,  // 7: idl.Agent.UpgradePrimaries:input_type -> idl.UpgradePrimariesRequest
	13, // 8: idl.Agent.RenameDirectories:input_type -> idl.RenameDirectoriesRequest
	15, // 9: idl.Agent.StopAgent:input_type -> idl.StopAgentRequest
	4,  // 10: idl.Agent.DeleteDataDirectories:input_type -> idl.DeleteDataDirectoriesRequest
	6,  // 11: idl.Agent.DeleteStateDirectory:input_type -> idl.DeleteStateDirectoryRequest
	8,  // 12: idl.Agent.DeleteTablespaceDirectories:input_type -> idl.DeleteTablespaceRequest
	10, // 13: idl.Agent.ArchiveLogDirectory:input_type -> idl.ArchiveLogDirectoryRequest
	19, // 14: idl.Agent.RsyncDataDirectories:input_type -> idl.RsyncRequest
	19, // 15: idl.Agent.Rsync:input_type -> idl.RsyncRequest
	23, // 16: idl.Agent.CheckDiskSpace:output_type -> idl.CheckDiskSpaceReply
	3,  // 17: idl.Agent.UpgradePrimaries:output_type -> idl.UpgradePrimariesReply
	14, // 18: idl.Agent.RenameDirectories:output_type -> idl.RenameDirectoriesReply
	16, // 19: idl.Agent.StopAgent:output_type -> idl.StopAgentReply
	5,  // 20: idl.Agent.DeleteDataDirectories:output_type -> idl.DeleteDataDirectoriesReply
	7,  // 21: idl.Agent.DeleteStateDirectory:output_type -> idl.DeleteStateDirectoryReply
	9,  // 22: idl.Agent.DeleteTablespaceDirectories:output_type -> idl.DeleteTablespaceReply
	11, // 23: idl.Agent.ArchiveLogDirectory:output_type -> idl.ArchiveLogDirectoryReply
	20, // 24: idl.Agent.RsyncDataDirectories:output_type -> idl.RsyncReply
	20, // 25: idl.Agent.Rsync:output_type -> idl.RsyncReply
	16, // [16:26] is the sub-list for method output_type
	6,  // [6:16] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_hub_to_agent_proto_init() }
func file_hub_to_agent_proto_init() {
	if File_hub_to_agent_proto != nil {
		return
	}
	file_cli_to_hub_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_hub_to_agent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TablespaceInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradePrimariesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataDirPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpgradePrimariesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataDirectoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteDataDirectoriesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStateDirectoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteStateDirectoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTablespaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTablespaceReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveLogDirectoryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArchiveLogDirectoryReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameDirectories); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameDirectoriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RenameDirectoriesReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopAgentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StopAgentReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckSegmentDiskSpaceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncPair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_hub_to_agent_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RsyncReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_hub_to_agent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_hub_to_agent_proto_goTypes,
		DependencyIndexes: file_hub_to_agent_proto_depIdxs,
		MessageInfos:      file_hub_to_agent_proto_msgTypes,
	}.Build()
	File_hub_to_agent_proto = out.File
	file_hub_to_agent_proto_rawDesc = nil
	file_hub_to_agent_proto_goTypes = nil
	file_hub_to_agent_proto_depIdxs = nil
}
